### ISSUE TITLE
--source-file-transfer=copy-git-others fails when there are untracked directories

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#1022]
```
‣  Copying in sources…
‣  (Unmounting image)
‣  (Detaching /dev/loop3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 614, in copy_file
    with open_close(newpath, os.O_WRONLY | os.O_CREAT | os.O_EXCL, st.st_mode) as newfd:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 571, in open_close
    fd = os.open(path, flags | os.O_CLOEXEC, mode)
FileExistsError: [Errno 17] File exists: '/var/tmp/mkosi-5xcvrum4/root/root/src/systemd-stable'
```

**Comment by DaanDeMeyer** [comment]
Fixed in main
