### ISSUE TITLE
Use of BaseImage fails with mount of mkosi-real-root

### ISSUE THREAD

**Issue by chymian** [systemd/mkosi#1028]
I'm trying to build  a multilayer Image for use in set of PortableServcies and on SBCs

A) creating a minimal Image:
```
[Distribution]
Distribution=debian
Release=bullseye
Mirror=http://mirror:3142/debian

[Output]
Format=gpt_squashfs
BootProtocols=uefi
Bootable=yes
Verity=true
ReadOnly=true
CompressFs=zstd
ImageId=eb8-oci-minimal
NoChown=true

[Content]
BasePackages=true
Packages=
    busybox-static
    btrfs-progs

PasswordIsHashed=false
Autologin=true

[Partition]
RootSize=1G

[Validation]
Checksum=true
```

B) The Base-Image, which is the next layer, basically  the same definition, but with some extra packages, files and the `BaseImage=`
```
[Distribution]
Distribution=debian
Release=bullseye
Mirror=http://mirror:3142/debian

[Output]
Format=gpt_squashfs
BootProtocols=uefi
Bootable=yes
Verity=true
ReadOnly=true

ImageId=eb8-oci-base
NoChown=true

[Content]
BasePackages=true
Packages=
        iputils-ping
        wget

PasswordIsHashed=true
Autologin=true
WithNetwork=true

[Partition]
BaseImage=../eb8-oci-minimal/mkosi.output/eb8-oci-minimal_0.3.raw
RootSize=1G
[Validation]
Checksum=true
```

calling mkosi on that configuration throws that error:
```
…snip…
The partition table has been altered.                                                                               
‣  Created image with partition table as /home/rsg/tc.images/images/oci-images/eb8-oci-base/mkosi.output/.mkosi-och4
ivqt                                                                                                                
‣  Using ../eb8-oci-minimal/mkosi.output/eb8-oci-minimal_0.3.raw as the base image
‣   Attaching ../eb8-oci-minimal/mkosi.output/eb8-oci-minimal_0.3.raw as loopback…
‣   Attached /dev/loop1                                                                                             
‣   Attaching /home/rsg/tc.images/images/oci-images/eb8-oci-base/mkosi.output/.mkosi-och4ivqt as loopback…
‣   Attached /dev/loop2
‣   Formatting ESP partition                              
mkfs.fat 4.2 (2021-01-31)                                 
‣   Mounting image…                                       
mount: /var/tmp/mkosi-4v25yg23/root/mkosi-real-root: wrong fs type, bad option, bad superblock on overlay, missing c
odepage or helper program, or other error.                                                                          
‣   (Detaching /dev/loop2)
‣   (Detaching /dev/loop1)                                                                                          
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)                               
  File "/root/.local/lib/python3.9/site-packages/mkosi/__main__.py", line 36, in <module>
    main()                                                
  File "/root/.local/lib/python3.9/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)                                           
  File "/root/.local/lib/python3.9/site-packages/mkosi/__init__.py", line 8409, in run_verb                         
    manifest = build_stuff(args)           
  File "/root/.local/lib/python3.9/site-packages/mkosi/__init__.py", line 7772, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/root/.local/lib/python3.9/site-packages/mkosi/__init__.py", line 7489, in build_image
    with mount_image(args, root, base_image, loopdev, encrypted.without_generated_root(args)):
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/root/.local/lib/python3.9/site-packages/mkosi/__init__.py", line 1568, in mount_image
    realroot, workdir = mount_overlay(args, base_image, root, root_read_only)                                       
  File "/root/.local/lib/python3.9/site-packages/mkosi/__init__.py", line 1521, in mount_overlay
    do_mount("overlay", realroot, options, type="overlay", read_only=read_only)
  File "/root/.local/lib/python3.9/site-packages/mkosi/__init__.py", line 1471, in do_mount                 
    run(cmd)                                                                                                        
  File "/root/.local/lib/python3.9/site-packages/mkosi/backend.py", line 779, in run                      
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)                 
  File "/usr/lib/python3.9/subprocess.py", line 528, in run                                          
    raise CalledProcessError(retcode, process.args,                                                                 
subprocess.CalledProcessError: Command '['mount', '-n', 'overlay', '/var/tmp/mkosi-4v25yg23/root/mkosi-real-root', '
-t', 'overlay', '-o', 'lowerdir=/dev/loop1,upperdir=/var/tmp/mkosi-4v25yg23/root/mkosi-real-root,workdir=/var/tmp/mk
osi-4v25yg23/root/overlayfs-workdirz_n5mym7']' returned non-zero exit status 32.                                    
```

it tries to  mount: `root/mkosi-real-root` and `root/overlayfs-workdirz_n5mym7`
out of the tmp-dir.

but its a empty path:
```
tree /var/tmp/mkosi-4v25yg23/
/var/tmp/mkosi-4v25yg23/
└── root
```

A Question raised: can one stack every type of image together, like lower layer a squashfs, intermediate layer directory, top layer btrfs(rw), or are there some caveats?

**Comment by cryptoknight** [comment]
I get this same error trying to use BaseImage in v13. dmesg output from the kernel (5.15) says `overlayfs: '/dev/loop18' not a directory`. Looking at the docs for [overlayfs](https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html), I see no indication that the upper or lowerdirs can be anything other than actual directories. Thus I think the `lowerdir=/dev/loop1` above is incorrect and the loop device with the base image needs to be mounted somewhere before being used in an overlay.

**Comment by DaanDeMeyer** [comment]
This should be fixed on git main, or at least the code has been sufficiently reworked that the original issue can no longer happen. Please report back if this still doesn't work for you
