### ISSUE TITLE
Building with skip final phase causes exception

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#1077]
Hopefully the traceback explains it all. There is nothing besides a very simple build script in the working directory.

```
# mkosi --format=directory --skip-final-phase=yes --build-script build-script.sh build
....
‣  Unmounting Package Cache
‣  Copying in build script…
‣  Copying in sources…
‣  Unmounting image
‣  Running build script…
I built something
‣  Removing artifacts from development build…
‣ Skipping (second) final image build phase.
‣ Linking image file…
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__main__.py", line 36, in <module>
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__main__.py", line 27, in main
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 8337, in run_verb
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 7725, in build_stuff
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 4726, in link_output
FileNotFoundError: [Errno 2] No such file or directory: '/root/.mkosi-z0eod00q/root' -> '/root/image'
```

```
# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by DaanDeMeyer** [comment]
Can we just check if `root` exists in link_output() instead?
