### ISSUE TITLE
Recording deb manifest fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#1105]
```
‣  Recording packages in manifest…
‣  (Unmounting image)
‣  (Detaching /dev/loop36)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rphibel/src/mkosi/mkosi/__main__.py", line 36, in <module>
    main()
  File "/home/rphibel/src/mkosi/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/home/rphibel/src/mkosi/mkosi/__init__.py", line 8138, in run_verb
    manifest = build_stuff(args)
  File "/home/rphibel/src/mkosi/mkosi/__init__.py", line 7490, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/home/rphibel/src/mkosi/mkosi/__init__.py", line 7239, in build_image
    manifest.record_packages(root)
  File "/home/rphibel/src/mkosi/mkosi/manifest.py", line 83, in record_packages
    self.record_deb_packages(root)
  File "/home/rphibel/src/mkosi/mkosi/manifest.py", line 152, in record_deb_packages
    installtime = datetime.fromtimestamp(int(installtime))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by DaanDeMeyer** [comment]
cc @bluca

**Comment by bluca** [comment]
interesting, I'll have a look when I got a moment
