### ISSUE TITLE
Cannot build bootable crossarch image

### ISSUE THREAD

**Issue by davide125** [systemd/mkosi#1155]
When building [this config](https://pagure.io/fedora-asahi/mkosi/blob/main/f/mkosi.default) on a Fedora 36 x86_64 host with `qemu-user-static-aarch64` installed I get:

```
‣  Installing boot loader…
Copied "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/efi/EFI/systemd/systemd-bootaa64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/efi/EFI/BOOT/BOOTAA64.EFI".
Random seed file /efi/loader/random-seed successfully written (32 bytes).
‣  Setting root password
‣  Recording packages in manifest…
‣  Resetting machine ID
‣  Removing random seed
‣  Trimming File System
/var/tmp/mkosi-2hu7fgt6/root: 2.4 GiB (2568028160 bytes) trimmed
‣  Unmounting image
‣  Mounting image…
‣  Generating combined kernel + initrd boot file…
objcopy: '/var/tmp/mkosi-2hu7fgt6/root/lib/systemd/boot/efi/linuxx64.efi.stub': No such file
objcopy: --change-section-vma .initrd=0x0000000003000000 never used
objcopy: --change-section-vma .linux=0x0000000002000000 never used
objcopy: --change-section-vma .cmdline=0x0000000000030000 never used
objcopy: --change-section-vma .osrel=0x0000000000020000 never used
‣  (Unmounting image)
‣  (Detaching /dev/loop1)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8409, in run_verb
    manifest = build_stuff(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7772, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7566, in build_image
    install_unified_kernel(args, root, root_hash, do_run_build_script, for_cache, cached, mount)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 4381, in install_unified_kernel
    run(cmd)
  File "/usr/lib/python3.10/site-packages/mkosi/backend.py", line 779, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib64/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['objcopy', '--add-section', '.osrel=/var/tmp/mkosi-2hu7fgt6/root/usr/lib/os-release', '--change-section-vma', '.osrel=0x20000', '--add-section', '.cmdline=/var/tmp/mkosi-2hu7fgt6/cmdline', '--change-section-vma', '.cmdline=0x30000', '--add-section', '.linux=/var/tmp/mkosi-2hu7fgt6/root/lib/modules/6.0.0-0.rc2.20220826git4c612826bec1.22.fc38.aarch64/vmlinuz', '--change-section-vma', '.linux=0x2000000', '--add-section', '.initrd=/var/tmp/mkosi-2hu7fgt6/root/efi/3e8c406ebe814e8187583a3c29f40eb3/6.0.0-0.rc2.20220826git4c612826bec1.22.fc38.aarch64/initrd', '--change-section-vma', '.initrd=0x3000000', '/var/tmp/mkosi-2hu7fgt6/root/lib/systemd/boot/efi/linuxx64.efi.stub', '/var/tmp/mkosi-2hu7fgt6/root/efi/EFI/Linux/mkosi-fedora-6.0.0-0.rc2.20220826git4c612826bec1.22.fc38.aarch64.efi']' returned non-zero exit status 1.
```

**Comment by DaanDeMeyer** [comment]
I think this was recently fixed by @bluca. Is this with the main branch or the stable release in Fedora?

**Comment by bluca** [comment]
Yes I fixed various issues with EFI binaries being hard-coded recently

**Comment by davide125** [comment]
This was with the version currently in f36, yes.

**Comment by bluca** [comment]
try again from main, it should work (hopefully)

**Comment by DaanDeMeyer** [comment]
After waiting for ages, I get:

> objcopy: /var/tmp/mkosi-wpsz5jpu/root/lib/systemd/boot/efi/linuxaa64.efi.stub: file format not recognized

**Comment by DaanDeMeyer** [comment]
Hmm, diving into it more, recent objcopy should support this (see https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=b69c9d41e89498442cb5af5287f378b3583dd445), but it isn't available in the objcopy on my system (f36).

**Comment by DaanDeMeyer** [comment]
So fedora ships binutils 2.37 but support for efi aarch64 in objcopy was only added in binutils 2.38 so I expect this to work out of the box from Fedora 37 onwards.

**Comment by leifliddy** [comment]
I'm running into the literally the same issue on F37 attempting to build this config https://github.com/leifliddy/asahi-fedora-builder/blob/main/mkosi.default on an `x86_64` system with `qemu-user-static-aarch64`. It was working fine in the recent past maybe like a couple months ago.

**Comment by DaanDeMeyer** [comment]
This should work assuming llvm-objcopy is installed on the system so let's close the issue, if this is still a problem, we can reopen
