### ISSUE TITLE
ExtraTree= pointing to a non-existent directory results in a backtrace

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#1167]
```console
$ ls mkosi.extra      
ls: cannot access 'mkosi.extra': No such file or directory

$ sudo mkosi build
‣  Copying in extra file trees…
‣  (Unmounting image)
‣  (Detaching /dev/loop0)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8409, in run_verb
    manifest = build_stuff(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7772, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7506, in build_image
    install_extra_trees(args, root, for_cache)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 3650, in install_extra_trees
    shutil.unpack_archive(cast(str, tree), root)
  File "/usr/lib64/python3.10/shutil.py", line 1302, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format '/home/zbyszek/pythonschool/vm/mkosi/mkosi.extra'
```

I guess we should check for presence before creating the whole image.

**Comment by keszybz** [comment]
https://github.com/python/cpython/issues/98758

I also see that mkosi doesn't print the summary to stdout, so grep doesn't work.
