### ISSUE TITLE
parse_bytes does not support float point

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#1168]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8385, in run_verb
    args = load_args(raw)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 6888, in load_args
    args.root_size = parse_bytes(args.root_size)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 6249, in parse_bytes
    result = int(num_bytes) * factor
ValueError: invalid literal for int() with base 10: '7.3'
```

floats are useful for users, and under Python it is no extra effort to support them.

**Comment by behrmann** [comment]
Which semantics did you have in mind? It could be as easy as exchanging `int` for `math.ceil`

**Comment by keszybz** [comment]
Just convert the whole thing to bytes, and round up to the closest sector boundary. E.g. '7.3g' should be 7838315520 bytes (assuming a sector is 512 bytes).
