### ISSUE TITLE
Partition removal failure when releasing loopback

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#1174]
Possible regression introduced by #1146.

Configuration
```INI
[Distribution]
Distribution = ubuntu
Release      = kinetic
Repositories = main,universe

[Output]
ImageId      = SysExt
ImageVersion = 0
Format       = gpt_squashfs
UsrOnly      = yes
Verity       = signed

# Testing showed the best performance with zstd and a 256K block size
Mksquashfs = mksquashfs -b 256K -quiet -noappend
Compress   = zstd

[Validation]
Checksum   = yes

[Partitions]
BaseImage       = mkosi.output/ubuntu~kinetic/Base_0
BuildScript     =
OutputDirectory = mkosi.output/sysext/
ExtraTrees      = mkosi.empty
PrepareScript   =

PostInstallationScript = mkosi.postinst-sysext

# Everything above is boilerplate. The real contents is the packages below.
[Content]
Packages = strace,network-manager-openconnect,nm-tray

```

Log output

```
The partition table has been altered.
‣     Writing partition...
‣    Inserting verity signature partition…
‣     Resizing disk image to 79.8M
‣     Inserting partition of 4.0K...
GPT PMBR size mismatch (163383 != 163391) will be corrected by write.
The backup GPT table is not on the end of the device. This problem will be corrected by write.
Disk /dev/loop3: 79.78 MiB, 83656704 bytes, 163392 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 94EE7593-B411-F14E-8CBB-C7A06270F59C

Old situation:

Device        Start    End Sectors  Size Type
/dev/loop3p1     40 162031  161992 79.1M Linux /usr (x86-64)
/dev/loop3p2 162032 163335    1304  652K Linux /usr verity (x86-64)
/dev/loop3p3 163336 163343       8    4K unknown

>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: 93720389-21FC-0A49-8049-F45E7C7431C5).
/dev/loop3p1: Created a new partition 1 of type 'Linux /usr (x86-64)' and of size 79.1 MiB.
Partition #1 contains a squashfs signature.
/dev/loop3p2: Created a new partition 2 of type 'Linux /usr verity (x86-64)' and of size 652 KiB.
Partition #2 contains a DM_verity_hash signature.
/dev/loop3p3: Created a new partition 3 of type 'unknown' and of size 4 KiB.
/dev/loop3p4: Done.

New situation:
Disklabel type: gpt
Disk identifier: 93720389-21FC-0A49-8049-F45E7C7431C5

Device        Start    End Sectors  Size Type
/dev/loop3p1     40 162031  161992 79.1M Linux /usr (x86-64)
/dev/loop3p2 162032 163335    1304  652K Linux /usr verity (x86-64)
/dev/loop3p3 163336 163343       8    4K unknown

The partition table has been altered.
‣     Writing partition...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__main__.py", line 36, in <module>
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__main__.py", line 27, in main
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 8215, in run_verb
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 7554, in build_stuff
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 7239, in build_image
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/__init__.py", line 992, in attach_image_loopback
  File "/usr/local/lib/python3.10/dist-packages/mkosi-13-py3.10.egg/mkosi/syscall.py", line 75, in blkpg_del_partition
OSError: [Errno 6] No such device or address
Root partition-type UUID: 1a62dfd1-f62b-af85-2ed5-557c94317783
```

**Comment by mcassaniti** [comment]
My bad, one of my out-of-tree patches was inserting the `verity-sig` partition twice and I didn't notice.
