### ISSUE TITLE
Running postinst script fails if UsrOnly is true.

### ISSUE THREAD

**Issue by VasilisMylonas** [systemd/mkosi#1202]
Host: Fedora 36 x86_64

Output:
```
‣  Installing boot loader…
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/BOOT/BOOTX64.EFI".
Random seed file /efi/loader/random-seed successfully written (32 bytes).
‣  Setting root password
‣  Mounting Package Cache
‣  Running postinstall script…
‣  (Unmounting Package Cache)
‣  (Unmounting image)
‣  (Detaching /dev/loop0)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8409, in run_verb
    manifest = build_stuff(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7772, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7514, in build_image
    run_postinst_script(args, root, loopdev, do_run_build_script, for_cache)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 3528, in run_postinst_script
    shutil.copy2(args.postinst_script, root_home(args, root) / "postinst")
  File "/usr/lib64/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/mkosi-b9y41ce0/home-root/postinst'
make: *** [Makefile:16: mkosi.output/disk.img] Error 1
```

Config for reference:
```
[Distribution]
Distribution=arch

[Output]
Output=disk.img
Format=gpt_ext4
Bootable=true
ReadOnly=true
Verity=true
KernelCommandLine=bgrt_disable quiet rd.shell=0
UsrOnly=true

[Content]
BasePackages=true
CleanPackageMetadata=true
```

**Comment by labichn** [comment]
Does the postinst script still fail if you drop `ReadOnly=true`? I don't think you need that with `UsrOnly=true`, in that case the /usr partition defaults to read-only automatically.

**Comment by labichn** [comment]
Weird! The following commands work on my machine running mkosi@main, any chance you're running an older version?

```bash
cd $(mktemp -d)
cat <<'EOF' > mkosi.conf
[Distribution]
Distribution=arch

[Output]
Output=disk.img
Format=gpt_ext4
Bootable=true
#ReadOnly=true
Verity=true
KernelCommandLine=bgrt_disable quiet rd.shell=0
UsrOnly=true

[Content]
BasePackages=true
CleanPackageMetadata=true
EOF
cat <<'EOF' > mkosi.postinst
#!/bin/sh
echo postinst
EOF
chmod a+x mkosi.postinst
sudo mkosi
# ...
# ‣     Running postinstall script…
# postinst
# ... completes successfully
```

**Comment by VasilisMylonas** [comment]
mkosi --version output is `mkosi 13` which from what I can see is the latest. Also worth noting that running your command on my machine installs Fedora 36 (the distro I am using) and it seems like it ignores mkosi.conf and just runs with the defaults.

**Comment by VasilisMylonas** [comment]
I also tried installing the main branch but the same issues occur (I double checked to make sure I was actually running the new mkosi).

**Comment by DaanDeMeyer** [comment]
UsrOnly= isn't a thing anymore so let's close this issue
