### ISSUE TITLE
Can't buid images with --bootable and --format directory or cpio

### ISSUE THREAD

**Issue by pyfisch** [systemd/mkosi#1214]
Before #1090 the combination of --bootable and --format=directory was rejected. Now an error occurs in `def install_boot_loader`. I'm not sure what the expected behavior is: the function calls `bootctl install` which sets ESP and EFI variables but these don't exist without a GPT image. Should the function be skipped?

cc @DaanDeMeyer 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/foo/mkosi/mkosi/__main__.py", line 36, in <module>
    main()
  File "/home/foo/mkosi/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/home/foo/mkosi/mkosi/__init__.py", line 8166, in run_verb
    manifest = build_stuff(config)
  File "/home/foo/mkosi/mkosi/__init__.py", line 7471, in build_stuff
    image = build_image(state, manifest=manifest)
  File "/home/foo/mkosi/mkosi/__init__.py", line 7193, in build_image
    install_boot_loader(state, loopdev, cached_tree)
  File "/home/foo/mkosi/mkosi/__init__.py", line 3223, in install_boot_loader
    assert loopdev is not None
AssertionError
```

**Comment by DaanDeMeyer** [comment]
Yeah it probably should, I think this is remnant from grub support. bootctl should be fine with directory output, so I think we can drop the loopdev assertion and just install the bootloader, no need to skip the function. Happy to accept a patch.
