### ISSUE TITLE
Allow populating an existing directory without removing it first

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/mkosi#1251]
Hey!

In https://github.com/systemd/mkosi-initrd/pull/8 I've came across a use case where I'd like `mkosi` to create an OS tree in an already existing directory, which is a mount point of an image.

This is useful when using mkosi to create an OS image with a more complex layout, i.e. LVM:

```bash
# Create a disk image with LVM layout
dd if=/dev/zero of=rootfs.img bs=1M count=3000
lodev="$(losetup --show -f -P rootfs.img)"  
echo "type=E6D6D379-F507-44C2-A23C-238F2A3DF928 bootable" | sfdisk -X gpt "$lodev"    
lvm pvcreate "${lodev}p1"                                                                                                                                     
lvm vgcreate "vg_root" "${lodev}p1"                                                   
lvm vgchange -ay "vg_root"                                                                                                                                    
lvm lvcreate -l 100%FREE -n lv0 "vg_root"                                                                                                                                                           
mkfs.ext4 -L "root" /dev/vg_root/lv0                                                  
                                        
# Populate the rootfs with a basic OS image                                           
mkdir mnt                                                                             
mount /dev/vg_root/lv0 mnt                                                            
mkosi -d fedora -r 36 --format=directory --output=mnt    
```

The last `mkosi` invocation currently ends up with an error:

```
$ sudo mkosi -d fedora -r 36 --format=directory --output=mnt  
‣ Error: Output path /home/fsumsal/sandbox/mkosi/mnt exists already. (Consider invocation with --force.)
```

However, with `--force` `mkosi` attempts to remove the directory first, which also ends up with an error:

```
$ sudo mkosi --force -d fedora -r 36 --format=directory --output=mnt
‣ Removing output files…
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8397, in run_verb
    unlink_output(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 6337, in unlink_output
    unlink_try_hard(args.output)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 6313, in unlink_try_hard
    shutil.rmtree(path)
  File "/usr/lib64/python3.10/shutil.py", line 730, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python3.10/shutil.py", line 728, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: '/home/fsumsal/sandbox/mkosi/mnt'
```

Is this already possible with some other combination of options that I'm just overlooking?

Currently I work around this by instructing `mkosi` to create the OS tree in a different directory and then just move things over, which is not particularly nice.

**Comment by behrmann** [comment]
I think this might need some gymnastics, because Debian for example doesn't let one debootstrap into a non-empty directory, which is why we already have two code paths for skeleton files. 

Maybe as a silly workaround, since Daan will touch all of this pretty soon: Would mounting a/the empty existing image as the output directory be an option with the contents you would like to have as skeleton files?

**Comment by behrmann** [comment]
My workaround idea was to give mkosi an empty directory to put the output into and mount an image there and put everything from the pre-generated image in there with a skeleton, either by first moving everything out into a temporary skeleton when reusing is the only option or by using the pre-generated image as the skeleton (after mounting it of course) and starting with a fresh image for the second step. 

Either would require your tweak to make mkosi accept that the directory is already there. 

But I'm speaking completely off the cuff here. No idea if this would work.
