### ISSUE TITLE
Fedora rawhide and GPG keyring error

### ISSUE THREAD

**Issue by rezib** [systemd/mkosi#1279]
With mkosi 14, I'm getting issues with Fedora rawhide and GPG keyring.

Packages in rawhide seems to be currently signed with Fedora 38 GPG key.

First, the default generic keyring `fedora.gpg` lacks the Fedora 38 key:

```
$ LANG=C sudo mkosi --distribution fedora --release rawhide
‣ Removing output files…
‣ Detaching namespace
‣ Setting up temporary workspace.
[…]
(149/149): python3-libs-3.11.0-1.fc38.x86_64.rpm                                                2.0 MB/s | 9.6 MB     00:04    
--------------------------------------------------------------------------------------------------------------------------------
Total                                                                                           8.5 MB/s |  65 MB     00:07     
warning: /var/tmp/mkosi-ha0251e2/root/var/cache/dnf/fedora-ebd04873699a984e/packages/alternatives-1.21-1.fc38.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID eb10b464: NOKEY
fedora                                                                                          9.2 kB/s |  10 kB     00:01    
Importing GPG key 0x5323552A:
 Userid     : "Fedora (37) <fedora-37-primary@fedoraproject.org>"
 Fingerprint: ACB5 EE4E 831C 74BB 7C16 8D27 F55A D3FB 5323 552A
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x38AB71F4:
 Userid     : "Fedora (36) <fedora-36-primary@fedoraproject.org>"
 Fingerprint: 53DE D2CB 922D 8B8D 9E63 FD18 999F 7CBF 38AB 71F4
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x9867C58F:
 Userid     : "Fedora (35) <fedora-35-primary@fedoraproject.org>"
 Fingerprint: 787E A6AE 1147 EEE5 6C40 B30C DB46 3971 9867 C58F
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x45719A39:
 Userid     : "Fedora (34) <fedora-34-primary@fedoraproject.org>"
 Fingerprint: 8C5B A699 0BDB 26E1 9F2A 1A80 1161 AE69 4571 9A39
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x9570FF31:
 Userid     : "Fedora (33) <fedora-33-primary@fedoraproject.org>"
 Fingerprint: 963A 2BEB 0200 9608 FE67 EA42 49FD 7749 9570 FF31
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0xDBBDCF7C:
 Userid     : "Fedora (iot 2019) <fedora-iot-2019@fedoraproject.org>"
 Fingerprint: C2A3 FA9D C67F 68B9 8BB5 43F4 7BB9 0722 DBBD CF7C
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x3228467C:
 Userid     : "Fedora (epel9) <epel@fedoraproject.org>"
 Fingerprint: FF8A D134 4597 106E CE81 3B91 8A38 72BF 3228 467C
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x2F86D6A1:
 Userid     : "Fedora EPEL (8) <epel@fedoraproject.org>"
 Fingerprint: 94E2 79EB 8D8F 25B2 1810 ADF1 21EA 45AB 2F86 D6A1
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91E9 7D7C 4A5E 96F1 7F3E 888F 6A2F AEA2 352C 64E5
 From       : https://getfedora.org/static/fedora.gpg
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for alternatives-1.21-1.fc38.x86_64.rpm is not installed. Failing package is: alternatives-1.21-1.fc38.x86_64
 GPG Keys are configured as: https://getfedora.org/static/fedora.gpg
[…]
Public key for zlib-1.2.12-5.fc38.x86_64.rpm is not installed. Failing package is: zlib-1.2.12-5.fc38.x86_64
 GPG Keys are configured as: https://getfedora.org/static/fedora.gpg
Error: GPG check FAILED
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 8254, in run_verb
    manifest = build_stuff(config)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7559, in build_stuff
    image = build_image(state, manifest=manifest)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7270, in build_image
    install_distribution(state, cached_tree)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2979, in install_distribution
    install(state)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2151, in install_fedora
    install_packages_dnf(state, packages)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2027, in install_packages_dnf
    invoke_dnf(state, 'install', packages)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 1991, in invoke_dnf
    run(cmdline, env=dict(KERNEL_INSTALL_BYPASS="1"))
  File "/usr/lib/python3/dist-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dnf', '-y', '--config=/var/tmp/mkosi-ha0251e2/dnf.conf', '--best', '--allowerasing', '--releasever=rawhide', '--installroot=/var/tmp/mkosi-ha0251e2/root', '--setopt=keepcache=1', '--setopt=install_weak_deps=0', '--noplugins', '--nodocs', 'install', 'dnf', 'systemd', 'util-linux']' returned non-zero exit status 1.
```

Unfortunately, forcing rawhide release to 38 doesn't help:

```
$ LANG=C sudo mkosi --distribution fedora --release rawhide-38
‣ Removing output files…
‣ Detaching namespace
‣ Setting up temporary workspace.
[…]
‣     Installing Fedora Linux…
Fedora rawhide — release version: 38
Fedora rawhide — release version: 38
‣      Mounting API VFS…
[…]
(149/149): python3-libs-3.11.0-1.fc38.x86_64.rpm                                                2.2 MB/s | 9.6 MB     00:04    
--------------------------------------------------------------------------------------------------------------------------------
Total                                                                                           7.5 MB/s |  65 MB     00:08     
warning: /var/tmp/mkosi-5_hoyfey/root/var/cache/dnf/fedora-ebd04873699a984e/packages/alternatives-1.21-1.fc38.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID eb10b464: NOKEY
fedora                                                                                          948  B/s | 260  B     00:00    
Status code: 404 for https://getfedora.org/static/keys/6A51BBABBA3D5467B6171221809A8D7CEB10B464.txt (IP: 2a05:d014:10:7803:f774:4d7c:e277:a457)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 8254, in run_verb
    manifest = build_stuff(config)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7559, in build_stuff
    image = build_image(state, manifest=manifest)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7270, in build_image
    install_distribution(state, cached_tree)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2979, in install_distribution
    install(state)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2151, in install_fedora
    install_packages_dnf(state, packages)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2027, in install_packages_dnf
    invoke_dnf(state, 'install', packages)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 1991, in invoke_dnf
    run(cmdline, env=dict(KERNEL_INSTALL_BYPASS="1"))
  File "/usr/lib/python3/dist-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dnf', '-y', '--config=/var/tmp/mkosi-5_hoyfey/dnf.conf', '--best', '--allowerasing', '--releasever=rawhide', '--installroot=/var/tmp/mkosi-5_hoyfey/root', '--setopt=keepcache=1', '--setopt=install_weak_deps=0', '--noplugins', '--nodocs', 'install', 'dnf', 'systemd', 'util-linux']' returned non-zero exit status 1.
```

The server gives a 404 for Fedora 38 key URL.

Is there any solution?

I guess this is more a Fedora bug rather than directly related to mkosi but I don't know how to proceed to ping Fedora maintainers. Maybe it is also a transient issue due to branching or migration in Fedora infrastructure?

**Comment by Conan-Kudo** [comment]
For what it's worth, these issues are [normally filed with Fedora Release Engineering](https://pagure.io/releng).

**Comment by nirik** [comment]
I am not sure if I can help, but I can try and direct you. ;) 

First, What is "the default generic keyring fedora.gpg" ? As far as I know we don't produce anything like that... 

Second, where are you getting the getfedora url there? "https://getfedora.org/static/keys/..."

Indeed the rawhide/f38 key isn't on there, but thats more a websites issue. See: https://pagure.io/fedora-web/websites/issue/141 for example.

**Comment by nirik** [comment]
I suppose https://src.fedoraproject.org/rpms/fedora-repos/raw/rawhide/f/RPM-GPG-KEY-fedora-38-primary ?
There's not really anything official here, most everyone using this key gets it from the fedora-repos rpm which they have installed. ;)

**Comment by Conan-Kudo** [comment]
You can get keys from `distribution-gpg-keys`. That's what I use for my image build descriptions.

**Comment by behrmann** [comment]
Well, getting keys from the repo is not an option for people running this on a different distro. ;) [This link](https://src.fedoraproject.org/rpms/fedora-repos/raw/rawhide/f/RPM-GPG-KEY-fedora-38-primary) looks fine, though, I'd be happy to review a PR switching us over to this.

**Comment by DaanDeMeyer** [comment]
Seems like this is not really an issue on our end, so let's close the issue. We can't depend on distribution specific packages as we should be able to build any target distro from any host distro that has the required tools.
