### ISSUE TITLE
bootctl: unrecognized option '--root'

### ISSUE THREAD

**Issue by vt-alt** [systemd/mkosi#1294]
We use mkosi to boot-test LKRG on GA on Ubuntu bionic, focal, jammy, kinetic. Since v15 [mkosi is unable to build images](https://github.com/lkrg-org/lkrg/issues/253) on any of these Ubuntus with:
```
dracut: Generating /boot/initrd.img-5.19.0-26-generic
‣   Installing boot loader…
bootctl: unrecognized option '--root'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 4512, in run_verb
    build_stuff(config)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 3857, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 3658, in build_image
    install_boot_loader(state)
  File "/usr/local/lib/python3.10/dist-packages/mkosi/__init__.py", line 790, in install_boot_loader
    run(["bootctl", "install", "--root", state.root], env={"SYSTEMD_ESP_PATH": "/boot"})
  File "/usr/local/lib/python3.10/dist-packages/mkosi/backend.py", line 742, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bootctl', 'install', '--root', '/home/runner/work/lkrg/mkosi.lkrg.tmpowqkk4y3/root']' returned non-zero exit status 1.
```
It seems even on latest Ubuntu _kinetic_ `bootctl` does not support `--root`:
```
root@ubuntu-kinetic:~# bootctl --root
bootctl: unrecognized option '--root'
```
How it should be used now when `WithUnifiedKernelImages` is dropped too?

**Comment by behrmann** [comment]
The `WithUnifiedKernelImages` is only dropped main branch, where you will need a bleeding edge repart, see #1290.

**Comment by vt-alt** [comment]
I see only `main` branch here, perhaps you suggesting to stay on `v14` tag? That's what I thought too.

**Comment by DaanDeMeyer** [comment]
Yes, main branch will only work if you build systemd from source and even then has breaking changes. Please stick to a release tag if you don't want to build systemd from source.

**Comment by vt-alt** [comment]
Thanks for suggestions.
