### ISSUE TITLE
Allow disabling mkosi's built-in default repository settings

### ISSUE THREAD

**Issue by WolfSkin0** [systemd/mkosi#1357]
I'm attempting to create a kali linux image with mkosi. Currently, I have the config using the kali repositories as the mirror, but every time I attempt to run the build, it insists on loading the debian security repositories and other repos that I never told it to load in the first place (like `kali-rolling-updates` which doesn't exist).
I have attempted to override the repositories in a number of ways, including by trying to override the apt config using the skeleton tree, however, all of that is just seemingly ignored.

The configuration I am using worked approximately 6 months ago, so I'm now completely stumped as to what I can/should do to actually make this work again, as I'm out of my depths trying to debug this.

Relevant config fields in mkosi.conf:
```
[Distribution]
Distribution=debian
Release=kali-rolling
Mirror=http://http.kali.org/kali

[Content]
Packages=
        #### Kali keyring (explicit install just in case)
	kali-archive-keyring

	#### Pattern Matching Madness. Please do not touch unless this changes in the official kali vm build repos
	?priority(standard) !?section(lib) !(~napt-listchanges|~ndebian-faq|~ndoc-debian|~npython3-reportbug|~nreportbug|~nwamerican)

	#### Core packages that we need
	kali-linux-core
	kali-linux-default
	linux-image-amd64
	linux-headers-amd64
```
`mkosi.skeleton/etc/apt/apt.conf.d/99-sigdel`: (this has worked in the past to get apt to not try to query the security repos, however no longer seems to be respected in the build)
```
APT::Get::AllowUnauthenticated "true";
APT::GET::Assume-Yes "true";
APT::GET::Fix-Broken "true";
Dir::Etc::sourceparts "sources.list.x";
```
`mkosi.skeleton/etc/apt/source.list`:
```
deb http://http.kali.org/kali kali-rolling main contrib non-free
```
Kali's repo key is present both on the host system and in `mkosi.skeleton/etc/apt/trusted.gpg.d/`

This is the error message I am getting:
```
‣      Copying in skeleton file trees…
‣      Mounting API VFS…
Ign:1 https://security.debian.org/debian-security kali-rolling-security InRelease
Err:2 https://security.debian.org/debian-security kali-rolling-security Release
  404  Not Found [IP: 151.101.66.132 443]
Hit:3 http://kali.download/kali kali-rolling InRelease
Ign:4 http://http.kali.org/kali kali-rolling-updates InRelease
Err:5 http://http.kali.org/kali kali-rolling-updates Release
  404  Not Found [IP: 192.99.200.113 80]
Get:6 http://kali.download/kali kali-rolling/contrib amd64 Packages [116 kB]
Get:7 http://kali.download/kali kali-rolling/non-free amd64 Packages [222 kB]
Reading package lists... Done
W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
W: No sandbox user '_apt' on the system, can not drop privileges
E: The repository 'https://security.debian.org/debian-security kali-rolling-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://http.kali.org/kali kali-rolling-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8258, in run_verb
    manifest = build_stuff(config)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7563, in build_stuff
    image = build_image(state, manifest=manifest)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7273, in build_image
    install_distribution(state, cached_tree)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 2979, in install_distribution
    install(state)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 2661, in install_debian
    install_debian_or_ubuntu(state)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 2610, in install_debian_or_ubuntu
    invoke_apt(state, "get", "update", ["--assume-yes"])
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 2471, in invoke_apt
    return run(cmdline, env=env, text=True, **kwargs)
  File "/usr/lib/python3.10/site-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/apt-get', '-o', 'Dir=/home/wolfskin/Downloads/Unified-Kali-Build-main/mkosi.workspace/fneajtqu/root', '-o', 'DPkg::Chroot-Directory=/home/wolfskin/Downloads/Unified-Kali-Build-main/mkosi.workspace/fneajtqu/root', '-o', 'APT::Architecture=amd64', '-o', 'dpkg::install::recursive::minimum=1000', 'update', '--assume-yes']' returned non-zero exit status 100.
```

Please let me know if there are bits of this that I should reformat or that I'm missing, as it's my first time filing a report here :sweat_smile:

**Comment by behrmann** [comment]
We don't support cross-building, i.e. building a Kali image from Debian. You can have a look at `mkosi/distributions/ubuntu.py` and add something similar for Kali for your usage.

**Comment by DaanDeMeyer** [comment]
What we can do now that we run apt on the host is implement --repository-directory for it. This is additive to the existing repositories but it might work for this use case?

**Comment by DaanDeMeyer** [comment]
So we should implement --repository-directory for Debian and Ubuntu once #1442 is in. And then extend the list parser to allow referring to the defaults used by mkosi via some string or so so that users can do `RepositoryDirectories=!default` to skip mkosi's defaults and then add their own. That should fix this use case. We can use the same mechanism for `Repositories=` as well.

**Comment by WolfSkin0** [comment]
I think that would be perfect! Many thanks :smile: 
Since my use-case literally involves more or less only changing the repositories, having to maintain a soft fork to add that change feels like overkill to me.

**Comment by DaanDeMeyer** [comment]
This should be possible again with the newly implemented --package-manager-tree option.
