### ISSUE TITLE
repart fails when building an image with verity as root

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#1392]
I'm encountering a problem when I try to build a verity enabled image as root. Using the configuration in https://github.com/Cornelicorn/mkosi-verity-test, I can build the image as an unprivileged user, but not as root.
When I build the image as root using
```
mkosi genkey
mkosi -f
```
I get the following error:
```
‣  Generating disk image
No machine ID set, using randomized partition UUIDs.
/dev/loop6 successfully formatted as ext4 (label "root-x86-64", uuid a676e1db-1ba9-4019-9564-791fc1718297)
Populating ext4 filesystem with files.
Successfully populated ext4 filesystem with files.
/dev/loop7 successfully formatted as ext4 (label "root-x86-64", uuid 53b7bfa9-602b-4ab6-86a0-f87d4239be1a)
Populating ext4 filesystem with files.
Successfully populated ext4 filesystem with files.
Automatically determined minimal disk image size as 1.3G.
Sized '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/staging/image.raw' to 1.3G.
Applying changes.
Wiped block device.
Discarded entire block device.
Successfully wiped file system signatures from future partition 1.
Successfully wiped file system signatures from future partition 2.
Successfully wiped file system signatures from future partition 3.
Copying in '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/.#repartf8a440bc56616a91' (1.0G) on block level into future partition 1.
Copying in of '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/.#repartf8a440bc56616a91' on block level completed.
Input/output error while creating hash area.
Failed to setup verity hash data: Input/output error
mkosi.run.RemoteException: Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/mkosi/__main__.py", line 3, in <module>
    mkosi.__main__.main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi/mkosi/__main__.py", line 36, in main
    run_verb(args)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 4012, in run_verb
    fork_and_wait(target)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 166, in fork_and_wait
    result = target()
             ^^^^^^^^
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 4007, in target
    build_stuff(uid, gid, config)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 3331, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 3217, in build_image
    roothash = invoke_repart(state, skip=("esp", "xbootldr"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 3158, in invoke_repart
    output = json.loads(run(cmdline, stdout=subprocess.PIPE, env=env).stdout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/mkosi/mkosi/run.py", line 220, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env=env, **kwargs,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
CalledProcessError: Command '['systemd-repart', '--empty=allow', '--size=auto', '--dry-run=no', '--json=pretty', '--root', '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/root', '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/staging/image.raw', '--empty=create', '--private-key', '/local_scratch/mkosi-test/sb.key', '--certificate', '/local_scratch/mkosi-test/sb.crt', '--defer-partitions', 'esp,xbootldr', '--definitions', '/local_scratch/mkosi-test/mkosi.repart']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/mkosi/__main__.py", line 3, in <module>
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/mkosi/mkosi/__main__.py", line 36, in main
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 4012, in run_verb
  File "/usr/local/bin/mkosi/mkosi/run.py", line 186, in fork_and_wait
subprocess.CalledProcessError: Command '['systemd-repart', '--empty=allow', '--size=auto', '--dry-run=no', '--json=pretty', '--root', '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/root', '/local_scratch/mkosi-test/.mkosi.tmppvpt1ies/staging/image.raw', '--empty=create', '--private-key', '/local_scratch/mkosi-test/sb.key', '--certificate', '/local_scratch/mkosi-test/sb.crt', '--defer-partitions', 'esp,xbootldr', '--definitions', '/local_scratch/mkosi-test/mkosi.repart']' returned non-zero exit status 1.
```
The underlying filesystem is `ext4`, I'm using Debian 12 with some systemd tools built from upstream, namely `bootctl,systemd-dissect,systemd-repart,ukify` built from `f5abe8f95721213edd76c16ed829cc3e37d7bdc6` and mkosi built as an zipapp from `f645a8df0fa52961592bb931ba0cf0e94441ea55`.

When I try to build the image as an unprivileged user, it succeeds. I can't mount the resulting image using `SYSTEMD_LOG_LEVEL=debug systemd-dissect --mount --read-only image.raw /mnt` with the following output:
```Opened '/local_scratch/mkosi-test/image.raw' in O_RDONLY access mode, with O_DIRECT enabled.
Determined sector size 512 based on discovered partition table.
Successfully acquired /dev/loop0, devno=7:0, nr=0, diskseq=14
Kernel was quicker than us in adding partition 1.
Opened /dev/loop0p1 (fd=3, whole_block_devnum=7:0, diskseq=14).
Kernel was quicker than us in adding partition 2.
Opened /dev/loop0p2 (fd=4, whole_block_devnum=7:0, diskseq=14).
Kernel was quicker than us in adding partition 3.
Opened /dev/loop0p3 (fd=7, whole_block_devnum=7:0, diskseq=14).
Kernel was quicker than us in adding partition 4.
Opened /dev/loop0p4 (fd=8, whole_block_devnum=7:0, diskseq=14).
No type detected on partition /dev/loop0p2
Signature data contains embedded NUL byte.
Failed to load verity signature partition: Invalid argument
Removed partition /dev/loop0p1
Removed partition /dev/loop0p2
Removed partition /dev/loop0p3
Removed partition /dev/loop0p4
```
but I guess that part is a problem with either `systemd-repart` or `systemd-dissect`?

**Comment by DaanDeMeyer** [comment]
Fixes for all reported issues in https://github.com/systemd/systemd/pull/26855

**Comment by Cornelicorn** [comment]
Yes, can confirm the patches from this branch work. Thanks for the blazingly fast fix :))

**Comment by Cornelicorn** [comment]
Closing, since https://github.com/systemd/systemd/pull/26855 was merged and this was never a mkosi issue.
