### ISSUE TITLE
WithDocs=yes breaks (at least) bootable Debian 12 build

### ISSUE THREAD

**Issue by Natureshadow** [systemd/mkosi#1418]
Creating a bootable image with Debian 12 fails if `WithDocs=yes` is set:

```ini
[Distribution]
Distribution=debian
Release=bookworm

[Output]
Format=gpt_btrfs
Bootable=yes

[Content]
Packages=less
WithDocs=yes

[Partitions]
RootSize=16G
HomeSize=8G
```

Interestingly, the build does not fail with anything related to docs, but because for some reason, setting this makes `mkosi` pull in `systemd-boot` already when installing the build image, instead of only for the final image.

**Comment by behrmann** [comment]
Could you provide the traceback?

**Comment by Natureshadow** [comment]
```plain
Errors were encountered while processing:
 systemd-boot
W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
E: Sub-process /usr/bin/dpkg returned an error code (1)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 8268, in run_verb
    manifest = build_stuff(config)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7573, in build_stuff
    image = build_image(state, manifest=manifest)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7284, in build_image
    install_distribution(state, cached_tree)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2993, in install_distribution
    install(state)
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2675, in install_debian
    install_debian_or_ubuntu(state)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2632, in install_debian_or_ubuntu
    invoke_apt(state, "get", "install", ["--assume-yes", *extra_packages])
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2485, in invoke_apt
    return run(cmdline, env=env, text=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/apt-get', '-o', 'Dir=/var/tmp/mkosi-djmb74b6/root', '-o', 'DPkg::Chroot-Directory=/var/tmp/mkosi-djmb74b6/root', '-o', 'APT::Architecture=amd64', '-o', 'dpkg::install::recursive::minimum=1000', 'install', '--assume-yes', 'systemd-resolved', 'linux-image-amd64', 'task-laptop', 'fish', 'dracut', 'systemd-sysv', 'dbus', 'task-cinnamon-desktop', 'task-german-desktop', 'systemd-boot', 'libpam-systemd', 'btrfs-progs', 'systemd']' returned non-zero exit status 100.
```

This is a follow-up error of:

```plain
Failed to write 'LoaderSystemToken' EFI variable: No such file or directory
dpkg: error processing package systemd-boot (--configure):
 installed systemd-boot package post-installation script subprocess returned error exit status 1
```

I traced this down to the existence of the `doc_paths` now. If the `doc_paths` exist, i.e. are not deleted, then `systemd-boot` is pulled in as dependency. If I let mkosi delete `doc_paths`, then it does not try to install `systemd-boot` in the build image… I am very confused.

**Comment by behrmann** [comment]
Which commit or version of mkosi are you on? Judging from the traceback this looks rather old. Could you check whether it works with the current `main`?

**Comment by Natureshadow** [comment]
Depends on what you call "old". It is `v14`, the most recent released version of mkosi.

I might be able to test with `main`, but I prefer using released versions.

**Comment by DaanDeMeyer** [comment]
We don't do stable releases, so the only way we can help is to fix this bug in main if it exists there as well. If you can reproduce on main we might be able to help out. Note that you either need to be running a rolling release or compile systemd from source and use `--extra-search-path <systemd-build-directory>` when running from main. We've also done quite a few breaking changes so your existing config likely won't work as is.

**Comment by Natureshadow** [comment]
> We don't do stable releases

Oh, you certainly did 14 times ;). Sorry for misunderstanding that ;)!

I will see what I can do.

**Comment by Natureshadow** [comment]
It seems that current `main` works with `WithDocs=yes`. Thus, closing this issue.
