### ISSUE TITLE
Unable to use package cache on Arch unless a bogus Release is set

### ISSUE THREAD

**Issue by fthiery** [systemd/mkosi#146]
Using the following mkosi.default, alongside to a cache folder mkosi.cache, running mkosi results in an error being related to the lack of release in the [Distribution] key.

```
$ mkdir mkosi.cache
$ cat mkosi.default
[Distribution]
Distribution=arch
$ mkosi
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 2904, in <module>
    main()
  File "/usr/bin/mkosi", line 2885, in main
    args = load_args()
  File "/usr/bin/mkosi", line 2403, in load_args
    find_cache(args)
  File "/usr/bin/mkosi", line 2269, in find_cache
    args.cache_path = "mkosi.cache/" + args.distribution.name + "~" + args.release
TypeError: must be str, not NoneType
```
Arch being a rolling distro, there is no such thing as a release (except maybe for the date ?) Checking https://github.com/systemd/systemd/blob/master/.mkosi/mkosi.arch does not reveal any specific syntax that would allow the use of the cache folder.

Putting in a random Release, like "Release=2017-09-06" does skip the aforementioned error, should we automatically try to fill the Release key of mkosi.default in the case of arch ? Or just tolerate the absence of args.distribution.name ?

**Comment by fthiery** [comment]
Given the following existing code, i guess that tolerating it is the way to go:
```
def install_arch(args, workspace, run_build_script):
    if args.release is not None:
        sys.stderr.write("Distribution release specification is not supported for Arch Linux, ignoring.\n")
```
