### ISSUE TITLE
debug option does not list categories

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1497]
`man man/mkosi.1`  explanation of `--debug`  is incorrect:
```
       --debug=
              Enable additional debugging output.  Takes a comma-separated list of arguments specifying the area of interest.  Pass any invalid value (e.g. empty)  to list currently accepted values.
```
Testing this does not list the accepted values and also shows a build attempt:
```
$ builddir/mkosi --debug empty
‣ Removing output files…
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/NAS/Sunny/SourceCode/mkosi/builddir/mkosi/__main__.py", line 3, in <module>
    mkosi.__main__.main()
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/srv/NAS/Sunny/SourceCode/mkosi/builddir/mkosi/mkosi/__main__.py", line 64, in main
    run_verb(load_args(args))
  File "/srv/NAS/Sunny/SourceCode/mkosi/builddir/mkosi/mkosi/__init__.py", line 2441, in run_verb
    fork_and_wait(target)
  File "/srv/NAS/Sunny/SourceCode/mkosi/builddir/mkosi/mkosi/run.py", line 171, in fork_and_wait
    result = target()
  File "/srv/NAS/Sunny/SourceCode/mkosi/builddir/mkosi/mkosi/__init__.py", line 2436, in target
    build_stuff(uid, gid, config)
  File "/srv/NAS/Sunny/SourceCode/mkosi/builddir/mkosi/mkosi/__init__.py", line 1886, in build_stuff
    workspace = tempfile.TemporaryDirectory(dir=config.workspace_dir or Path.cwd(), prefix=".mkosi.tmp")
  File "/usr/lib/python3.9/tempfile.py", line 918, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib/python3.9/tempfile.py", line 498, in mkdtemp
    _os.mkdir(file, 0o700)
PermissionError: [Errno 13] Permission denied: '/srv/NAS/Sunny/SourceCode/mkosi/.mkosi.tmpd11b6mq9'
```

**Comment by DaanDeMeyer** [comment]
We made --debug a boolean option so no need for categories anymore

**Comment by iam-TJ** [comment]
In which case `mkosi.md` needs updating since it currently says:
```
--debug=`
: Enable additional debugging output. Takes a comma-separated list of
  arguments specifying the area of interest. Pass any invalid value
  (e.g. empty) to list currently accepted values.
```

**Comment by DaanDeMeyer** [comment]
You're not on the latest version, mkosi.md on the main branch is already updated.
