### ISSUE TITLE
RFE: Support multiple Packages= in same file

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1507]
This is a discussion item and request for enhancement. I've been reworking complex multi-distro config files. De-duplicating repeats and using `Match` clauses for `Distribution` and `PathExists` to trigger conditional inclusion.

Whilst doing that, for Debian and Ubuntu, I created single config files that use `Packages=?priority(important)`  and then a list of packages NOT to include that would otherwise come from the priority. There are varying reasons for not including each package so I placed them on separate `Packages=` lines with commentary attached but discovered this breaks Python's `configparser` (even when the file only matches a different distribution) with e.g:
```
$ cat mkosi-conf.d/21-packages-ubuntu-important.conf
[Match]
Distribution=ubuntu

[Content]
# 21-packages-debian-important.conf will be used too
Packages=?priority(important)
# don't need the Debian keyring
Packages=!debian-archive-keyring
# not needed
Packages=!ubuntu-advantage-tools

$ mkosi --distribution=debian summary
‣ Hint: mkosi failed because of an internal exception DuplicateOptionError, rerun mkosi with --debug to get more information
```
It would be 'nice' if this was possible without having to combine on a single line (its preferable to be able to record easily in associated comments why packages are included/excluded) and without having to create a separate file to contain each internal duplicate. I'm thinking of how `systemd` handles multiple `ExecStart=`  with `Type=oneshot` for example.

Of course the major difference I'm wishing for is to combine rather than replace prior instances (in the same file).

**Comment by iam-TJ** [comment]
Ahhh, One key but multiple lines - that may just be enough; thanks... but it doesn't work in my scenario since `?priority(important)` isn't expanded to the actual package list I'm trying to exclude a few packages from. It seems because the excluded package isn't in the verbatim list then there is no way to remove it in this way:
```
$ cat mkosi.conf.d/21-packages-debian-impotant.conf
[Match]
Distribution=debian ubuntu

[Content]
# Debian/Ubuntu packages with Priority: important
# Only those required for a non PID 1 lightweight generic OS container (not application container which would need less)
Packages=?priority(important)
         less
         !cron
         !groff-base
         !ifupdown
         !init
         !man-db

# less is more and easier to use!

$ mkosi --debug run --distribution=debian summary
...
CONTENT:
                  Packages: less
                            gawk
                            locales-all
                            locales
                            less
                            ?priority(important)
                            ?priority(required)
        With Documentation: no
```
What *does* work is to use another `apt` specific flag that signals removal for `apt-get install...` - suffix the package name with a hyphen:
```
...
[Content]
# Debian/Ubuntu packages with Priority: important
# Only those required for a non PID 1 lightweight generic OS container (not application container which would need less)
Packages=?priority(important)
         less
         cron-
         groff-base-
         ifupdown-
         init-
         man-db-
...
$ mkosi --distribution=debian summary
...
CONTENT:
                  Packages: less
                            gawk
                            locales-all
                            locales
                            man-db-
                            init-
                            ifupdown-
                            groff-base-
                            cron-
                            less
                            ?priority(important)
                            ?priority(required)
        With Documentation: no
```
Thanks as always for your quick response and pointer - lef me to a reasonable solution!

**Comment by iam-TJ** [comment]
Unfortunately using the `?priority(x)` technique fails due to how `mkosi`  wrap the arguments to `apt-get`:
```
$ sudo env -u SUDO_UID mkosi --debug run --distribution=debian --release=bullseye |& tee /tmp/mkosi.log

...
Reading package lists...
‣ + bwrap --unshare-pid --dev-bind / / --chdir /home/tj/iam/mkosi/debian-amd64-base --tmpfs /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/run --tmpfs /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/tmp --proc /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/proc --dev /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/dev --ro-bind /sys /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/sys --bind /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/var-tmp /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/var/tmp --die-with-parent --bind /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/etc/passwd /etc/passwd --bind /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/etc/group /etc/group --bind /dev/null /etc/shadow --bind /dev/null /etc/gshadow sh -c 'chmod 1777 /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/tmp /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/var/tmp /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/dev/shm && exec apt-get install less gawk locales-all locales '"'"'?priority(important)'"'"' man-db- init- ifupdown- groff-base- cron- less '"'"'?priority(required)'"'"' || exit $?'
Reading package lists...
Building dependency tree...
Reading state information...
E: input:0-20: error: Unrecognized pattern '?priority'
   ?priority(important)
   ^^^^^^^^^^^^^^^^^^^^
E: Unable to locate package ?priority(important)
E: Couldn't find any package by glob '?priority(important)'
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '?priority(important)'
E: input:0-19: error: Unrecognized pattern '?priority'
   ?priority(required)
   ^^^^^^^^^^^^^^^^^^^
E: Unable to locate package ?priority(required)
E: Couldn't find any package by glob '?priority(required)'
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '?priority(required)'
...
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/mkosi/__main__.py", line 3, in <module>
    mkosi.__main__.main()
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi/mkosi/__main__.py", line 64, in main
    run_verb(load_args(args))
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2441, in run_verb
    fork_and_wait(target)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 171, in fork_and_wait
    result = target()
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2436, in target
    build_stuff(uid, gid, config)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1918, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1787, in build_image
    install_distribution(state, cached)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 293, in install_distribution
    state.installer.install_packages(state, state.config.packages)
  File "/usr/local/bin/mkosi/mkosi/distributions/debian.py", line 129, in install_packages
    invoke_apt(state, "install", packages)
  File "/usr/local/bin/mkosi/mkosi/distributions/debian.py", line 221, in invoke_apt
    return run_with_apivfs(state, ["apt-get", operation, *extra], env=env)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 320, in run_with_apivfs
    die(f'"{shlex.join(str(s) for s in cmd)}" returned non-zero exit code {e.returncode}.')
  File "/usr/local/bin/mkosi/mkosi/log.py", line 27, in die
    raise exception or RuntimeError(message)
RuntimeError: "apt-get install less gawk locales-all locales '?priority(important)' man-db- init- ifupdown- groff-base- cron- less '?priority(required)'" returned non-zero exit code 100.

```

**Comment by iam-TJ** [comment]
I've now built `apt` v2.6.0 that supports `?priority(x)` and the build continues with the expanded package list. It has however revealed another issue which I think is caused by the package ordering of the apt-patterns:
```
The following NEW packages will be installed:                                                                                                                              
...                                          
The following held packages will be changed:                                                                                                                               
  cron ifupdown init                                                                                                                                                       
0 upgraded, 101 newly installed, 0 to remove and 0 not upgraded.                                                                                                           
E: Held packages were changed and -y was used without --allow-change-held-packages. 
...
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/mkosi/__main__.py", line 3, in <module>
    mkosi.__main__.main()
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi/mkosi/__main__.py", line 64, in main
    run_verb(load_args(args))
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2441, in run_verb
    fork_and_wait(target)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 171, in fork_and_wait
    result = target()
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2436, in target
    build_stuff(uid, gid, config)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1918, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1787, in build_image
    install_distribution(state, cached)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 293, in install_distribution
    state.installer.install_packages(state, state.config.packages)
  File "/usr/local/bin/mkosi/mkosi/distributions/debian.py", line 129, in install_packages
    invoke_apt(state, "install", packages) 
  File "/usr/local/bin/mkosi/mkosi/distributions/debian.py", line 221, in invoke_apt
    return run_with_apivfs(state, ["apt-get", operation, *extra], env=env)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 320, in run_with_apivfs
    die(f'"{shlex.join(str(s) for s in cmd)}" returned non-zero exit code {e.returncode}.')
  File "/usr/local/bin/mkosi/mkosi/log.py", line 27, in die
    raise exception or RuntimeError(message)
RuntimeError: "apt-get install less gawk locales-all locales '?priority(important)' man-db- init- ifupdown- groff-base- cron- less '?priority(required)'" returned non-zero
 exit code 100.
```
It would only require a one-line patch to resolve which adds: `APT::Get::allow-change-held-packages "true";` but then those held packages are re-added to the list of files to be installed and do get installed!
```
...
The following NEW packages will be installed:
  ... cron ...
  ... ifupdown init
  ...
The following held packages will be changed:
  cron ifupdown init
0 upgraded, 101 newly installed, 0 to remove and 0 not upgraded.
Need to get 45.5 MB of archives.
After this operation, 342 MB of additional disk space will be used.
Get:1 http://security.debian.org/debian-security bullseye-security/main amd64 libgnutls30 amd64 3.7.1-5+deb11u3 [1340 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 libext2fs2 amd64 1.46.2-2 [257 kB]
...
```
 I think that is due to the ordering of the `?priority(x)` entries so I'll investigate having `mkosi/distributions/debian.py` sort `packages` list to put any `?*` operators first, and any `package-` removals at the end.

**Comment by iam-TJ** [comment]
I have successfully patched `mkosi/distributions/debian.py` to correctly sort the package list and it works nicely but doesn't solve the issue since apt expands the patterns only *after* reading the `word-`  removal phrases, so ends up re-adding the package!
So I've altered the approach and instead use `mkosi`'s `RemovePackages=`  !  I've not managed to test this through to a successful image as yet because I've now hit another bug in unrelated code so will report that!

The patch I used is:
```
diff --git a/mkosi/distributions/debian.py b/mkosi/distributions/debian.py
index 6c047c8..d847147 100644
--- a/mkosi/distributions/debian.py
+++ b/mkosi/distributions/debian.py
@@ -123,6 +123,18 @@ class DebianInstaller(DistributionInstaller):
         policyrcd.write_text("#!/bin/sh\nexit 101\n")
         policyrcd.chmod(0o755)
 
+        # sort apt-patterns ("?xxxx") to head, removals ("word-") to tail, keep options at head ("-o...")
+        def mysort(mykey: str):
+            if mykey[-1] == "-":
+                return "~"
+            if mykey[0:2] == "-o":
+                return " "
+            return mykey[0:]
+
+        print(f">>> Packages {packages}")
+        packages.sort(key=mysort)
+        print(f">>> Packages {packages}")
+
         setup_apt(state, cls.repositories(state))
         invoke_apt(state, "update")
         invoke_apt(state, "install", packages)
@@ -180,6 +192,7 @@ def setup_apt(state: MkosiState, repos: Sequence[str]) -> None:
             APT::Install-Recommends "false";
             APT::Get::Assume-Yes "true";
             APT::Get::AutomaticRemove "true";
+            APT::Get::allow-change-held-packages "true";
             APT::Sandbox::User "root";
             Dir::Cache "{state.cache}";
             Dir::State "{state.workspace / "apt"}";
```
