### ISSUE TITLE
Debian: apt ?priority(x) breaks install

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1510]
Making this a bug report after initially discussing it in issue #1507

Unfortunately using the `?priority(x)` technique fails due to how `mkosi`  wrap the arguments to `apt-get`:
```
$ sudo env -u SUDO_UID mkosi --debug run --distribution=debian --release=bullseye |& tee /tmp/mkosi.log

...
Reading package lists...
‣ + bwrap --unshare-pid --dev-bind / / --chdir /home/tj/iam/mkosi/debian-amd64-base --tmpfs /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/run --tmpfs /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/tmp --proc /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/proc --dev /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/dev --ro-bind /sys /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/sys --bind /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/var-tmp /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/var/tmp --die-with-parent --bind /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/etc/passwd /etc/passwd --bind /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/etc/group /etc/group --bind /dev/null /etc/shadow --bind /dev/null /etc/gshadow sh -c 'chmod 1777 /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/tmp /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/var/tmp /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmp6_jf0yof/root/dev/shm && exec apt-get install less gawk locales-all locales '"'"'?priority(important)'"'"' man-db- init- ifupdown- groff-base- cron- less '"'"'?priority(required)'"'"' || exit $?'
Reading package lists...
Building dependency tree...
Reading state information...
E: input:0-20: error: Unrecognized pattern '?priority'
   ?priority(important)
   ^^^^^^^^^^^^^^^^^^^^
E: Unable to locate package ?priority(important)
E: Couldn't find any package by glob '?priority(important)'
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '?priority(important)'
E: input:0-19: error: Unrecognized pattern '?priority'
   ?priority(required)
   ^^^^^^^^^^^^^^^^^^^
E: Unable to locate package ?priority(required)
E: Couldn't find any package by glob '?priority(required)'
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '?priority(required)'
...
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/mkosi/__main__.py", line 3, in <module>
    mkosi.__main__.main()
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi/mkosi/__main__.py", line 64, in main
    run_verb(load_args(args))
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2441, in run_verb
    fork_and_wait(target)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 171, in fork_and_wait
    result = target()
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2436, in target
    build_stuff(uid, gid, config)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1918, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1787, in build_image
    install_distribution(state, cached)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 293, in install_distribution
    state.installer.install_packages(state, state.config.packages)
  File "/usr/local/bin/mkosi/mkosi/distributions/debian.py", line 129, in install_packages
    invoke_apt(state, "install", packages)
  File "/usr/local/bin/mkosi/mkosi/distributions/debian.py", line 221, in invoke_apt
    return run_with_apivfs(state, ["apt-get", operation, *extra], env=env)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 320, in run_with_apivfs
    die(f'"{shlex.join(str(s) for s in cmd)}" returned non-zero exit code {e.returncode}.')
  File "/usr/local/bin/mkosi/mkosi/log.py", line 27, in die
    raise exception or RuntimeError(message)
RuntimeError: "apt-get install less gawk locales-all locales '?priority(important)' man-db- init- ifupdown- groff-base- cron- less '?priority(required)'" returned non-zero exit code 100.

```

**Comment by DaanDeMeyer** [comment]
Yeah using this needs a recent apt, nothing we can do about that in mkosi

**Comment by iam-TJ** [comment]
I'm building latest `apt`  for now - Debian bookworm (testing) has v2.6.0 so once that becomes stable this won't be (so much) of an issue.
