### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bootctl'

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1515]
Building a BTRFS subvolume container image and hit this - seems to be assuming this is a virtual machine or bare metal disk image:
```
$ sudo env -u SUDO_UID mkosi --distribution=debian --release=bullseye summary
COMMANDS:
                      verb: summary
                   cmdline: 

DISTRIBUTION
              Distribution: debian
                   Release: bullseye
              Architecture: x86_64
                    Mirror: http://deb.debian.org/debian
      Local Mirror (build): none
  Repo Signature/Key check: yes
              Repositories: 
                   Initrds: 

OUTPUT:
                  Image ID: None
             Image Version: None
             Output Format: subvolume
          Manifest Formats: json
          Output Directory: default
       Workspace Directory: default
                    Output: /home/tj/iam/mkosi/debian-amd64-base/image
           Output Checksum: n/a
          Output Signature: n/a
    Output nspawn Settings: /home/tj/iam/mkosi/debian-amd64-base/image.nspawn
               Incremental: no
               Compression: none
       Kernel Command Line: 
           UEFI SecureBoot: no
       SecureBoot Sign Key: none
    SecureBoot Certificate: none
...
```
When building it ends with
```
$ sudo env -u SUDO_UID mkosi --distribution=debian --release=bullseye
...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
‣   Setting root password                                                            
‣   Copying in extra file trees… 
...
‣   Running kernel-install…                                                          
‣   Installing boot loader…   
‣ + bootctl install --root /home/tj/iam/mkosi/debian-amd64-base/.mkosi.tmpun55ywrb/root
‣ bootctl not found in PATH. 
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/mkosi/__main__.py", line 3, in <module>
    mkosi.__main__.main()
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi/mkosi/__main__.py", line 64, in main
    run_verb(load_args(args))
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2441, in run_verb
    fork_and_wait(target)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 171, in fork_and_wait
    result = target()
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 2436, in target
    build_stuff(uid, gid, config)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1918, in build_stuff
    build_image(state, manifest=manifest)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 1798, in build_image
    install_boot_loader(state)
  File "/usr/local/bin/mkosi/mkosi/__init__.py", line 503, in install_boot_loader
    run(["bootctl", "install", "--root", state.root], env={"SYSTEMD_ESP_PATH": "/boot"})
  File "/usr/local/bin/mkosi/mkosi/run.py", line 243, in run
    die(f"{cmdline[0]} not found in PATH.", e)
  File "/usr/local/bin/mkosi/mkosi/log.py", line 27, in die
    raise exception or RuntimeError(message)
  File "/usr/local/bin/mkosi/mkosi/run.py", line 234, in run
    return subprocess.run(cmdline,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bootctl'
```

**Comment by DaanDeMeyer** [comment]
Specify --bootable no to not make it bootable.

**Comment by iam-TJ** [comment]
Shouldn't a BTRFS subvol default to `--bootable no`  (assuming bootable is specifically about starting via a kernel)?

All my configurations for earlier (subvol) versions of mkosi do not have it set and do not experience this.

Modifying the existing configurations to work with v15 is identifying a lot of breaking changes that are requiring a lot of head-scratching and investigation!
