### ISSUE TITLE
btrfs subvolumes (UseSubvolumes=true) still not working

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1569]
Trying the latest code it is still not possible to get a subvolume output; it is just a directory copy:
```
$ ls -idlatr mkosi.output/{.,debian}* mkosi.cache mkosi.workspace
 440832 drwxrwx---  1 root root       168 2021-04-27 10:46 mkosi.output/debian_bullseye_amd64_0.2
 457953 -rw-rw----  1 root root        62 2023-04-24 13:50 mkosi.output/debian_bullseye_amd64_0.2.nspawn
 440538 drwxr-xr-x  1 root root        70 2023-05-20 13:23 mkosi.output/debian~bullseye
 457954 -rw-r--r--  1 root root     17806 2023-05-20 13:23 mkosi.output/debian_bullseye_amd64_0.2.manifest
 457955 lrwxrwxrwx  1 root root        25 2023-05-20 13:23 mkosi.output/debian_bullseye_amd64 -> debian_bullseye_amd64_0.2
    256 drwxr-x---+ 1 root machines   484 2023-05-20 13:23 mkosi.workspace
    256 drwxr-x---+ 1 root machines   484 2023-05-20 13:23 mkosi.output/.
    256 drwxr-x---+ 1 root machines   484 2023-05-20 13:23 mkosi.cache
```
Each of `mkosi.cache` , `mkosi.workspace` and `mkosi.output` are bind mounts to `/var/lib/machines/` which is the root of a BTRFS, as can be seen by the inode numbers above (256).
```
$ mount | grep mkosi
/dev/mapper/SUNNY-Machines on /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
/dev/mapper/SUNNY-Machines on /home/tj/iam/mkosi/debian-amd64-base/mkosi.output type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
/dev/mapper/SUNNY-Machines on /home/tj/iam/mkosi/debian-amd64-base/mkosi.cache type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
```
I instrumented the code with a function tracer and there is only a single call related to BTRFS when the workspace is being created:
```
$ grep '^. TRACE:' /tmp/mkosi/mkosi.log  | grep -B 2 btrfs
‣ TRACE:                  /srv/NAS/Sunny/SourceCode/mkosi/mkosi/distributions/debian.py:15:DebianInstaller() 
‣ TRACE:          /srv/NAS/Sunny/SourceCode/mkosi/mkosi/state.py:47:root() 
‣ TRACE:          /srv/NAS/Sunny/SourceCode/mkosi/mkosi/btrfs.py:10:btrfs_maybe_make_subvolume()
```
Configuration fragment:
```
$ cat mkosi.conf.d/95-output.conf 
[Output]
Format=directory
UseSubvolumes=true
Bootable=False
ImageId=debian_bullseye_amd64
ImageVersion=0.2

$ mkosi --distribution debian --release bullseye summary

PRESET: default

    COMMANDS:
                          verb: summary
                       cmdline: 

    DISTRIBUTION:
                  Distribution: debian
                       Release: bullseye
                  Architecture: x86_64
                        Mirror: http://deb.debian.org/debian
          Local Mirror (build): none
      Repo Signature/Key check: yes
                  Repositories: 

    OUTPUT:
                      Image ID: debian_bullseye_amd64
                 Image Version: 0.2
                 Output Format: directory
              Manifest Formats: json
              Output Directory: /home/tj/iam/mkosi/debian-amd64-base/mkosi.output
           Workspace Directory: /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace
               Cache Directory: /home/tj/iam/mkosi/debian-amd64-base/mkosi.cache/debian~bullseye
               Build Directory: none
             Install Directory: none
                        Output: debian_bullseye_amd64_0.2
               Output Checksum: n/a
              Output Signature: n/a
        Output nspawn Settings: debian_bullseye_amd64_0.2.nspawn
                   Compression: none
...
```
Note: this was without my patch to fix the illegal machine names containing "_".

**Comment by iam-TJ** [comment]
With additional debugging it seems that the missing functionality to attempt a btrfs snapshot is in build_image():
```
$ grep '^. in build_image' /tmp/mkosi/mkosi.log 
‣ in build_image() for f in state.staging.iterdir() doing shutil.move('/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpiqrqmzkx/staging/debian_bullseye_amd64_0.2', '/home/tj/iam/mkosi/debian-amd64-base/mkosi.output')
‣ in build_image() for f in state.staging.iterdir() doing shutil.move('/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpiqrqmzkx/staging/debian_bullseye_amd64_0.2.nspawn', '/home/tj/iam/mkosi/debian-amd64-base/mkosi.output')
‣ in build_image() for f in state.staging.iterdir() doing shutil.move('/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpiqrqmzkx/staging/debian_bullseye_amd64_0.2.manifest', '/home/tj/iam/mkosi/debian-amd64-base/mkosi.output')
‣ in build_image() doing '/home/tj/iam/mkosi/debian-amd64-base/mkosi.output'.joinpath('debian_bullseye_amd64').symlink_to('debian_bullseye_amd64_0.2')
```

**Comment by DaanDeMeyer** [comment]
This happens because shutil.move() tries to rename first before falling back to copying. rename() across mountpoints is not supported, even if they're the same source, so we end up copying.

It's possible to pass a custom copy function to shutil.move() so we'd need to write such a function that tries to snapshot if subvolumes are enabled and we're moving a directory first and only then falls back to doing a regular copy.

**Comment by iam-TJ** [comment]
I added a workaround over the weekend that works for subvols and falls back to using the copy in `btrfs_maybe_snapshot_volume()`
```
diff --git a/mkosi/__init__.py b/mkosi/__init__.py
index d1eb25b..213ec21 100644
--- a/mkosi/__init__.py
+++ b/mkosi/__init__.py
@@ -1703,8 +1703,9 @@ def build_image(uid: int, gid: int, args: MkosiArgs, config: MkosiConfig) -> Non
         for f in state.staging.iterdir():
             if not f.is_dir():
                 os.chown(f, uid, gid)
-
-            shutil.move(f, state.config.output_dir)
+                shutil.move(f, state.config.output_dir)
+            else:
+                btrfs_maybe_snapshot_subvolume(state.config, f, state.config.output_dir.joinpath(f.name))
 
         if not state.config.output_dir.joinpath(state.config.output).exists():
             state.config.output_dir.joinpath(state.config.output).symlink_to(state.config.output_with_compression)
```

It looks like a custom function that for subvolumes calls `btrfs_maybe_snapshot_volume()` would do the job? Would that be the correct approach? Should that function continue to call `copy_path()`  in which case it could be the custom function itself ?

If it's not one thing it's another! I used the bind mounts to get around a bubblewrap failure if using symbolic links, which would cause early failure with for example:
```
Reading package lists...                                                                                                                                                   
‣ + bwrap --unshare-pid --dev-bind / / --chdir /home/tj/iam/mkosi/debian-amd64-base --die-with-parent --tmpfs /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.t
mp9f1u5c4u/root/run ...
 ...
s findutils grep gzip hostname libaudit-common libcap-ng0 libaudit1 libcrypt1 debconf libpam0g libdb5.3 libpam-modules-bin libpam-modules libpam-runtime login ncurses-bin 
perl-base sed libblkid1 libmount1 libsmartcols1 libudev1 libuuid1 util-linux-extra util-linux libdebconfclient0 base-passwd usr-is-merged init-system-helpers libc-bin ncur
ses-base sysvinit-utils || exit $?'                                                  
bwrap: Can't mkdir parents for /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp9f1u5c4u/root/run: No such file or directory                                 
...
Traceback (most recent call last): 
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                                                                       
    return _run_code(code, main_globals, None,                                                                                                                             
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code                                                                                                                
    exec(code, run_globals)                                                                                                                                                
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 53, in <module>                                                                                           
    main()                                                                                                                                                                 
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner                                                                                                               
    return func(*args, **kwds)                                                       
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 49, in main         
    run_verb(args, presets)                                                          
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2070, in run_verb                                                                                         
    fork_and_wait(target)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 171, in fork_and_wait
    result = target()
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2064, in target
    build_image(uid, gid, args, config)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1652, in build_image 
    install_distribution(state)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 241, in install_distribution
    state.installer.install(state)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/distributions/debian.py", line 109, in install
    cls.install_packages(state, [Path(deb).name.partition("_")[0] for deb in essential])
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/distributions/debian.py", line 124, in install_packages
    invoke_apt(state, "install", packages, apivfs=apivfs)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/distributions/debian.py", line 225, in invoke_apt
    return bwrap(["apt-get", operation, *extra], apivfs=state.root if apivfs else None, env=env | state.environment)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 335, in bwrap
    raise e
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 329, in bwrap
    result = run([*cmdline, template.format(shlex.join(str(s) for s in cmd))],
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 244, in run
    raise e
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 231, in run
    return subprocess.run(cmdline,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
```

**Comment by DaanDeMeyer** [comment]
Btw, why make things complicated with bind mounts? Why not just set WorkspaceDirectory=/var/lib/machines, CacheDirectory=/var/lib/machines and OutputDirectory=/var/lib/machines? Then you won't have the rename issue

**Comment by iam-TJ** [comment]
> Btw, why make things complicated with bind mounts? Why not just set WorkspaceDirectory=/var/lib/machines, CacheDirectory=/var/lib/machines and OutputDirectory=/var/lib/machines? Then you won't have the rename issue

Output/Workspace/Cache may well be to different targets (`/usr/lib/machines/`., `/usr/local/lib/machines/`) and using the in-built facility to control those via the file-system `mkosi.xxxx` nodes  is a really useful separation of configuration and operations.

Sym-links worked fine until bubblewrap was added - that is what needs the mounts.

The aim is to divorce the project written configuration from the build file-system layout.

In my use-case there are thousands of containers being (re)generated across multiple host environments from a single central tree of mkosi configurations, starting from a base template and overlaying additional container/application-specific configuration (The added `Match` functionality has made that much easier to do).

**Comment by DaanDeMeyer** [comment]
Try the latest commits on https://github.com/systemd/mkosi/pull/1692, that should fix it.

**Comment by iam-TJ** [comment]
It looks like not:
```
$ git l -n 16
4968f89 2023-07-21 22:10:21 +0100 N Tj Merge commit 'refs/pull/1692/head' of https://github.com/systemd/mkosi
cce7086 2023-07-21 22:11:58 +0200 N Daan De Meyer Add move_tree()
bc8fbe5 2023-07-21 22:11:58 +0200 N Daan De Meyer Don't try to snapshot files in copy_tree()
bfcc136 2023-07-21 22:11:52 +0200 N Daan De Meyer Rename btrfs.py to tree.py and move copy_tree() into it
21bd99b 2023-07-21 21:17:46 +0200 N Daan De Meyer Rename copy_path() to copy_tree()
ff60349 2023-07-21 21:17:42 +0200 N Daan De Meyer Remove unused state argument from maybe_compress()
56aad1e 2023-07-21 20:02:58 +0100 N Tj Merge remote-tracking branch 'DaanDeMeyer/stuff'
51da1ad 2023-07-21 20:48:11 +0200 N Daan De Meyer mount_passwd() cleanups
adf0f79 2023-07-21 20:38:46 +0200 N Daan De Meyer Make MkosiState a context manage
```
Gives:
```
final: BUILDROOT=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpm_o34uyd/root OUTPUTDIR=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpm_o3
4uyd/staging
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.3.manifest
‣ + cp --recursive --preserve=mode,timestamps,links,xattr,ownership --no-target-directory --reflink=auto /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpm_o
34uyd/staging/debian-bookworm-amd64_0.3 /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.3
‣ + cp --recursive --preserve=mode,timestamps,links,xattr,ownership --no-target-directory --reflink=auto /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpm_o
34uyd/staging/debian-bookworm-amd64_0.3.nspawn /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.3.nspawn
‣ + cp --recursive --preserve=mode,timestamps,links,xattr,ownership --no-target-directory --reflink=auto /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpm_o
34uyd/staging/debian-bookworm-amd64_0.3.manifest /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.3.manifest
‣  /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64 size is 414.7M.
‣ Increasing last component of version by one, bumping '0.3' → '0.4'.
# clear builtins._
```
But:
```
$ sudo btrfs subvolume list mkosi.output
ID 316 gen 2041 top level 5 path lineage-builder
ID 317 gen 698 top level 316 path lineage-builder/home
ID 318 gen 698 top level 316 path lineage-builder/srv
ID 319 gen 698 top level 316 path lineage-builder/var
ID 320 gen 698 top level 319 path lineage-builder/var/tmp
ID 321 gen 698 top level 319 path lineage-builder/var/lib/machines
ID 479 gen 2442 top level 5 path .mkosi.cache
```

**Comment by DaanDeMeyer** [comment]
Nvm had a stupid bug, please try again

**Comment by iam-TJ** [comment]
You're working as late as me! I added this `print()` and the result is below:
```
$ git diff mkosi/tree.py 
diff --git a/mkosi/tree.py b/mkosi/tree.py
index 437199f..ce9f32d 100644
--- a/mkosi/tree.py
+++ b/mkosi/tree.py
@@ -56,6 +56,7 @@ def copy_tree(config: MkosiConfig, src: Path, dst: Path, *, preserve_owner: bool
         src, dst,
     ]
 
+    print(f'subvolume={subvolume} preserve_owner={preserve_owner} dst.is_dir()={dst.is_dir()} statfs(src)={statfs(src)} src.stat().st_ino={src.stat().st_ino} dst.exists()={dst.exists()} any(dst.iterdir())={any(dst.iterdir())}')
     # Subvolumes always have inode 256 so we can use that to check if a directory is a subvolume.
     if not subvolume or not preserve_owner or not dst.is_dir() or statfs(src) != "btrfs" or src.stat().st_ino != 256 or (dst.exists() and any(dst.iterdir())):
         run(copy)
```
gives:
```
final: BUILDROOT=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpsn92nlod/root OUTPUTDIR=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpsn92
nlod/staging
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.4.manifest
‣ + stat --file-system --format %T /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpsn92nlod/staging
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 52, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 48, in main
    run_verb(args, presets)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2232, in run_verb
    build_image(args, config)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1822, in build_image
    finalize_staging(state)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1747, in finalize_staging
    move_tree(state.config, f, state.config.output_dir)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/tree.py", line 93, in move_tree
    copy_tree(config, src, dst)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/tree.py", line 59, in copy_tree
    print(f'subvolume={subvolume} preserve_owner={preserve_owner} dst.is_dir()={dst.is_dir()} statfs(src)={statfs(src)} src.stat().st_ino={src.stat().st_ino} dst.exists()=
{dst.exists()} any(dst.iterdir())={any(dst.iterdir())}')
                                                                                                                                                                           
                                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 932, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4'
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True any(dst.iterdir())=False
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True any(dst.iterdir())=False
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161906 dst.exists()=True any(dst.iterdir())=True
# clear builtins._
```

**Comment by iam-TJ** [comment]
I added the `src` and `dst` directory names to the above patch so we know what it is considering. It looks to me as if `src` is never a subvol.
```
final: BUILDROOT=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxlpqtc/root OUTPUTDIR=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxl
pqtc/staging
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.4.manifest
‣ + stat --file-system --format %T /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxlpqtc/staging
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 52, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 48, in main
    run_verb(args, presets)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2232, in run_verb
    build_image(args, config)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1822, in build_image
    finalize_staging(state)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1747, in finalize_staging
    move_tree(state.config, f, state.config.output_dir)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/tree.py", line 95, in move_tree
    copy_tree(config, src, dst)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/tree.py", line 61, in copy_tree
    print(f'subvolume={subvolume} preserve_owner={preserve_owner} dst.is_dir()={dst.is_dir()} statfs(src)={statfs(src)} src.stat().st_ino={src.stat().st_ino} dst.exists()={dst.exists()} any(dst.iterdir())={any(dst.iterdir())}')
                                                                                                                                                                                                              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 932, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4'
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.skeleton
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxlpqtc/pkgmngr
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True any(dst.iterdir())=False
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.skeleton
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxlpqtc/root
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True any(dst.iterdir())=False
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.extra
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxlpqtc/root
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161906 dst.exists()=True any(dst.iterdir())=True
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_yxlpqtc/staging/debian-bookworm-amd64_0.4
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4
# clear builtins._

```

**Comment by DaanDeMeyer** [comment]
What happens if you use `--use-subvolumes yes`?

**Comment by iam-TJ** [comment]
```
tj@sunny:~/iam/mkosi/debian-amd64-base$ sudo debug=true ./build.sh --use-subvolumes yes --distribution=debian --release=bookworm --image-id debian-bookworm-amd64 --auto-bump --force build
...
$ grep -E '^(dst|src)|subvol' /tmp/mkosi/mkosi.5.log 
‣ + btrfs subvolume create /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp2wf205_c/root
Create subvolume '/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp2wf205_c/root'
    print(f'subvolume={subvolume} preserve_owner={preserve_owner} dst.is_dir()={dst.is_dir()} statfs(src)={statfs(src)} src.stat().st_ino={src.stat().st_ino} dst.exists()={dst.exists()} any(dst.iterdir())={any(dst.iterdir())}')
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.skeleton
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp2wf205_c/pkgmngr
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True any(dst.iterdir())=False
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.skeleton
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp2wf205_c/root
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True any(dst.iterdir())=False
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.extra
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp2wf205_c/root
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161906 dst.exists()=True any(dst.iterdir())=True
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp2wf205_c/staging/debian-bookworm-amd64_0.4
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4
```

**Comment by DaanDeMeyer** [comment]
@iam-TJ One more fix, can you try again?

**Comment by iam-TJ** [comment]
Yay!
```
$ sudo btrfs subvol list mkosi.output
ID 316 gen 2041 top level 5 path lineage-builder
ID 317 gen 698 top level 316 path lineage-builder/home
ID 318 gen 698 top level 316 path lineage-builder/srv
ID 319 gen 698 top level 316 path lineage-builder/var
ID 320 gen 698 top level 319 path lineage-builder/var/tmp
ID 321 gen 698 top level 319 path lineage-builder/var/lib/machines
ID 479 gen 2442 top level 5 path .mkosi.cache
ID 540 gen 2631 top level 5 path debian-bookworm-amd64_0.4
```
Log:
```
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.4.manifest
‣ + stat --file-system --format %T /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4
‣ + stat --file-system --format %T /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4
‣ + btrfs subvolume snapshot /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4 /home/tj/iam/mkosi/debian-amd64-base
/mkosi.output/debian-bookworm-amd64_0.4
Create a snapshot of '/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4' in '/home/tj/iam/mkosi/debian-amd64-base/m
kosi.output/debian-bookworm-amd64_0.4'
‣ + stat --file-system --format %T /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4.nspawn
‣ + cp --recursive --preserve=mode,timestamps,links,xattr,ownership --no-target-directory --reflink=auto /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv72
67cg4/staging/debian-bookworm-amd64_0.4.nspawn /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4.nspawn
‣ + stat --file-system --format %T /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4.manifest
‣ + cp --recursive --preserve=mode,timestamps,links,xattr,ownership --no-target-directory --reflink=auto /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv72
67cg4/staging/debian-bookworm-amd64_0.4.manifest /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4.manifest
‣  /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64 size is 414.7M.
‣ Increasing last component of version by one, bumping '0.4' → '0.5'.
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.skeleton
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/pkgmngr
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True 
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.skeleton
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/root
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161916 dst.exists()=True 
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.extra
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/root
subvolume=True preserve_owner=False dst.is_dir()=True statfs(src)=ext2/ext3 src.stat().st_ino=3161906 dst.exists()=True 
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4
subvolume=True preserve_owner=True dst.is_dir()=False statfs(src)=btrfs src.stat().st_ino=256 dst.exists()=False 
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4.nspawn
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4.nspawn
subvolume=True preserve_owner=True dst.is_dir()=False statfs(src)=btrfs src.stat().st_ino=717296 dst.exists()=False 
src=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpv7267cg4/staging/debian-bookworm-amd64_0.4.manifest
dst=/home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64_0.4.manifest
subvolume=True preserve_owner=True dst.is_dir()=False statfs(src)=btrfs src.stat().st_ino=717297 dst.exists()=False 
# clear builtins._
```
