### ISSUE TITLE
Making initrd fails with permission denied on unprivileged builds.

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#1581]
Hi,
when building a minimal bootable image,

```ini
[Output]
Format=disk
Bootable=yes

[Content]
Packages=
    linux-image-cloud-amd64
    systemd
    systemd-boot
    systemd-sysv
    udev
    dbus
```

on Debian 12, I get the following error when building the image

```
‣  Building initrd
‣ + timedatectl show -p Timezone --value
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → CLOSING
Failed to parse bus message: Transport endpoint is not connected
Bus n/a: changing state CLOSING → CLOSED
‣   Removing output files…
‣ + btrfs subvolume create /local_scratch/hoffmac00/test/.mkosi.tmp2tuuzpge/root
ERROR: not a btrfs filesystem: /local_scratch/hoffmac00/test/.mkosi.tmp2tuuzpge
‣ + mkdir -p /local_scratch/hoffmac00/test
‣ + mkdir -p '/local_scratch/hoffmac00/test/.mkosi.tmp9g3uholq/cache/debian~bookworm'
mkdir: cannot create directory ‘/local_scratch/hoffmac00/test/.mkosi.tmp9g3uholq’: Permission denied
‣ "mkdir -p '/local_scratch/hoffmac00/test/.mkosi.tmp9g3uholq/cache/debian~bookworm'" returned non-zero exit code 1.
Traceback (most recent call last):
File "/usr/local/bin/mkosi", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__main__.py", line 49, in main
    run_verb(args, presets)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__init__.py", line 2100, in run_verb
    fork_and_wait(target)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/run.py", line 172, in fork_and_wait
    result = target()
             ^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__init__.py", line 2094, in target
    build_image(uid, gid, args, config)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__init__.py", line 1706, in build_image
    install_unified_kernel(state, roothash)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__init__.py", line 798, in install_unified_kernel
    build_image(state.uid, state.gid, args, config)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__init__.py", line 1660, in build_image
    make_cache_dir(state)
  File "/usr/local/lib/python3.11/dist-packages/mkosi/__init__.py", line 1307, in make_cache_dir
    run(["mkdir", "-p", state.cache],
  File "/usr/local/lib/python3.11/dist-packages/mkosi/run.py", line 249, in run
    raise e
  File "/usr/local/lib/python3.11/dist-packages/mkosi/run.py", line 236, in run
    return subprocess.run(cmdline,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
CalledProcessError: Command '['mkdir', '-p', '/local_scratch/hoffmac00/test/.mkosi.tmp9g3uholq/cache/debian~bookworm']' returned non-zero exit status 1.
```

If I add a sleep before the `mkdir` call, I can see that `/local_scratch/hoffmac00/test/.mkosi.tmp9g3uholq/cache` is owned by `1000000000:1000000000`, which is the first uid in my subuid range.

Setting `--cache-dir` mitigates the problem.
I also noticed that during the main build without specifiying a cache dir, `/local_scratch/hoffmac00/test/.mkosi.tmp9g3uholq/cache`directly contains `archives,pkgcache.bin,srcpkgcache.bin`, whereas when setting a cache dir, this is stored in the `debain~bookworm` subdirectory.
Since the initrd is built by specifying `--cache-dir` in [__init__.py](https://github.com/systemd/mkosi/blob/85d8342e974e5537529ea959b4e405fa330467b9/mkosi/__init__.py#L774), this subdirectory is created at first instead of reusing the actual cache.

I guess [this piece of code](https://github.com/systemd/mkosi/blob/main/mkosi/config.py#L2176) should be moved outside of the config parsing, so that this is handled the same way everywhere.

**Comment by Cornelicorn** [comment]
> Can you try #1582?

Yes, that solves it.
