### ISSUE TITLE
Loading secureboot keys with `LoadCredential` does not work

### ISSUE THREAD

**Issue by Cornelicorn** [systemd/mkosi#1611]
I'm trying to generate images from within a systemd unit with an unprivileged user. I want the units to be secureboot signed and don't want the user to have permanent access to the secureboot keys, so I want to use `LoadCredential` in the unit.
When I do this, the unit fails with
```
‣   Signing systemd-boot binaries…
‣ + sbsign --key /run/credentials/test-mkosi.service/sbkey --cert /run/credentials/test-mkosi.service/sbcrt --output /test/test/.mkosi.tmpxmvfbxp4/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed /test/test/.mkosi.tmp>
warning: data remaining[122880 vs 139035]: gaps between PE/COFF sections?
warning: data remaining[122880 vs 139040]: gaps between PE/COFF sections?
Can't load key from file '/run/credentials/test-mkosi.service/sbkey'
403794C8717F0000:error:8000000D:system library:BIO_new_file:Permission denied:../crypto/bio/bss_file.c:67:calling fopen(/run/credentials/test-mkosi.service/sbkey, r)
403794C8717F0000:error:10080002:BIO routines:BIO_new_file:system lib:../crypto/bio/bss_file.c:77:
‣ "sbsign --key /run/credentials/test-mkosi.service/sbkey --cert /run/credentials/test-mkosi.service/sbcrt --output /test/test/.mkosi.tmpxmvfbxp4/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed /test/test/.mkosi.tmpx>
None
None
Traceback (most recent call last):
File "/usr/local/bin/mkosi", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/__main__.py", line 51, in main
    run_verb(args, presets)
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/__init__.py", line 2145, in run_verb
    fork_and_wait(target)
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/run.py", line 172, in fork_and_wait
    result = target()
             ^^^^^^^^
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/__init__.py", line 2139, in target
    build_image(args, config, uid, gid)
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/__init__.py", line 1723, in build_image
    install_boot_loader(state)
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/__init__.py", line 461, in install_boot_loader
    run(["sbsign",
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/run.py", line 249, in run
    raise e
  File "/opt/zedv/venvs/venvs/mkosi/lib/python3.11/site-packages/mkosi/run.py", line 236, in run
    return subprocess.run(cmdline,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
CalledProcessError: Command '['sbsign', '--key', '/run/credentials/test-mkosi.service/sbkey', '--cert', '/run/credentials/test-mkosi.service/sbcrt', '--output', '/test/test/.mkosi.tmpxmvfbxp4/root/usr/lib/systemd/boot/efi/sys>
test-mkosi.service: Main process exited, code=exited, status=1/FAILURE
test-mkosi.service: Failed with result 'exit-code'.
Failed to start test-mkosi.service.
test-mkosi.service: Consumed 25.791s CPU time.

```

This is a minimal reproducer on debian bookworm:

```bash
mkdir -p /test/test
cd /test

mkosi genkey

chown -R cnhof:cnhof /test

cat >/etc/systemd/system/test-sbsign.service <<EOF
[Service]
Type=oneshot
WorkingDirectory=/test/test

User=cnhof
LoadCredential=sbkey:/test/mkosi.key
LoadCredential=sbcrt:/test/mkosi.crt

ExecStart=/usr/bin/sbsign --key="%d/sbkey" --cert="%d/sbcrt" /boot/vmlinuz-6.1.0-9-amd64 --output test.kernel
EOF

cat >/etc/systemd/system/test-mkosi.service <<EOF
[Service]
Type=oneshot
WorkingDirectory=/test/test

User=cnhof
LoadCredential=sbkey:/test/mkosi.key
LoadCredential=sbcrt:/test/mkosi.crt

ExecStart=/usr/local/bin/mkosi --force --sign-expected-pcr false --secure-boot true --secure-boot-key="%d/sbkey" --secure-boot-certificate="%d/sbcrt" --extra-search-path /usr/share/zedv/mkosi/systemd-source/build --package=linux-image-generic,systemd,systemd-boot,systemd-sysv,udev,dbus --bootable
EOF
```

The unit `test-sbsign` exits successfully, the unit `test-mkosi` doesn't. If I run mkosi as root instead of as an unprivileged user, the signing succeeds.

It also works if I add a `RuntimeDirectory` and copy the keys to there and use them from there, the build also succeeds.
With my cp invocation, the permissions stay the same, but the group of the file changes to `cnhof`, i.e. the group of the unprivileged user.

**Comment by DaanDeMeyer** [comment]
So credentials can only be read by the user running the service. When running unprivileged, we switch user to a uidmap user which won't be able to read the credentials. We would have to copy all input files to a more permissive location so we can still read them after switching to the user namespace.

**Comment by DaanDeMeyer** [comment]
This seems like a bug in the credentials logic. We should be able to access credentials as long as we map the service user into the user namespace which we do.

I opened https://github.com/systemd/systemd/issues/28747 to track this in systemd so let's close this one and follow up there. We can reopen this if the credentials behavior in systemd is intended.
