### ISSUE TITLE
Matching multiple values needs to be documented in the man page

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1690]
Some recent commit broke the Match behaviour:
```
$ cat mkosi.conf.d/30-package-ssh-server.conf
[Match]
Distribution=debian ubuntu
PathExists=../match/ssh-server

[Content]
Packages=openssh-server
```
Now results in:
```
# code object from /srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py
‣ 'debian ubuntu' is not a valid Distribution
Traceback (most recent call last):
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 275, in parse_enum
    return type(value)
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 'debian ubuntu' is not a valid Distribution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 19, in propagate_failed_return
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 43, in main
    args, presets = MkosiConfigParser().parse()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 1763, in parse
    self.parse_config(Path("."), namespace)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 1544, in parse_config
    self.parse_config(p if p.is_file() else Path("."), namespace)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 1511, in parse_config
    result = match(s.dest, v, namespace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 294, in config_match_enum
    return cast(bool, make_enum_parser(type)(value) == getattr(namespace, dest))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 277, in parse_enum
    die(f"'{value}' is not a valid {type.__name__}")
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/log.py", line 30, in die
    sys.exit(1)
SystemExit: 1
```
Prior to this the code worked so one config fragment can match on multiple distributions.

**Comment by behrmann** [comment]
The syntax has been reworked to be more like systemd's condition syntax, i.e. it should work when prepending a `|` to make this a triggering condition like this
```
Distribution=|debian
Distribution=|ubuntu
```
an example is in the tests, but it *is* missing documentation.

**Comment by iam-TJ** [comment]
Thanks for the quick response  - saved me a LOT of frustration and code-digging! `=!` works although it does lead to a lot of repetition.

Now onto the next failure `chroot: cannot change root directory to '/work/postinst': No such file or directory` - expect another report once I have dug into it!

**Comment by DaanDeMeyer** [comment]
This is already documented in the `Configuration Settings` section
