### ISSUE TITLE
Cannot build Fedora image on Ubuntu

### ISSUE THREAD

**Issue by shvchk** [systemd/mkosi#1696]
Ubuntu 23.04, mkosi 14

<details><summary><code>apt list --installed rpm dnf binutils llvm linux-generic</code></summary><p>

```
binutils/lunar-updates,lunar-security,now 2.40-2ubuntu4.1 amd64 [installed]
dnf/lunar,lunar,now 4.14.0-3 all [installed]
linux-generic/lunar-updates,lunar-security,now 6.2.0.25.25 amd64 [installed]
llvm/lunar,now 1:15.0-56~exp2 amd64 [installed]
rpm/lunar,now 4.18.0+dfsg-1build1 amd64 [installed]
```
</p>
</details> 

<details><summary><code>tree</code></summary><p>

```
.
├── mkosi.cache
├── mkosi.default
├── mkosi.extra
│   ├── etc
│   │   └── systemd
│   │       ├── journald.conf
│   │       └── network
│   │           ├── eth.network
│   │           └── host.network
│   └── root
└── mkosi.output
```
</p>
</details> 

<details><summary>Config</summary><p>

```ini
[Distribution]
Distribution=fedora
Release=rawhide # using 38 still triggers GPG key not found issue #1279

[Output]
ImageId=fedora_test
Format=gpt_ext4
QCow2=yes
Bootable=yes
SecureBoot=no
KernelCommandLine=net.ifnames=0

[Validation]
CheckSum=yes

[Content]
Password=XXX
PasswordIsHashed=yes
WithNetwork=yes
```
</p>
</details> 

Log:

```
Complete!
‣      Unmounting API VFS…
‣    Unmounting Package Cache
‣    Setting root password
‣    Copying in extra file trees…
‣    Generating initramfs images…
/usr/bin/dracut: line 1056: /sys/module/firmware_class/parameters/path: No such file or directory
dracut: No '/dev/log' or 'logger' included for syslog logging
‣    Installing boot loader…
Failed to open boot loader directory /usr/lib/systemd/boot/efi: No such file or directory
‣ Error: Workspace command bootctl install returned non-zero exit code 1.
```

Ok, let's create that dir: `mkdir -p mkosi.extra/usr/lib/systemd/boot/efi` and rerun mkosi:

```
Complete!
‣      Unmounting API VFS…
‣    Unmounting Package Cache
‣    Setting root password
‣    Copying in extra file trees…
‣    Generating initramfs images…
/usr/bin/dracut: line 1056: /sys/module/firmware_class/parameters/path: No such file or directory
dracut: No '/dev/log' or 'logger' included for syslog logging
‣    Installing boot loader…
⚠ Mount point '/efi' which backs the random seed file is world accessible, which is a security hole! ⚠
⚠ Random seed file '/efi/loader/.#bootctlrandom-seedacfe79096e79af5f' is world accessible, which is a security hole! ⚠
Random seed file /efi/loader/random-seed successfully written (32 bytes).
‣    Recording packages in manifest…
‣    Resetting machine ID
‣    Removing random seed
‣    Trimming File System
/var/tmp/mkosi-h5nk8fuh/root: 2,6 GiB (2771075072 bytes) trimmed
‣   Unmounting image…
‣   Mounting image…
‣    Generating combined kernel + initrd boot file…
objcopy: '/var/tmp/mkosi-h5nk8fuh/root/lib/systemd/boot/efi/linuxx64.efi.stub': No such file
objcopy: --change-section-vma .initrd=0x3000000 never used
objcopy: --change-section-vma .linux=0x2000000 never used
objcopy: --change-section-vma .cmdline=0x30000 never used
objcopy: --change-section-vma .osrel=0x20000 never used
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 45, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 41, in main
    run_verb(a)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 8268, in run_verb
    manifest = build_stuff(config)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7573, in build_stuff
    image = build_image(state, manifest=manifest)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7356, in build_image
    install_unified_kernel(state, root_hash, mount)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 4094, in install_unified_kernel
    run(cmd)
  File "/usr/lib/python3/dist-packages/mkosi/backend.py", line 860, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, env={**os.environ, **env}, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['objcopy', '--add-section', '.osrel=/var/tmp/mkosi-h5nk8fuh/root/usr/lib/os-release', '--change-section-vma', '.osrel=0x20000', '--add-section', '.cmdline=/var/tmp/mkosi-h5nk8fuh/cmdline', '--change-section-vma', '.cmdline=0x30000', '--add-section', '.linux=/var/tmp/mkosi-h5nk8fuh/root/lib/modules/6.5.0-0.rc2.20230719gitccff6d117d8d.18.fc39.x86_64/vmlinuz', '--change-section-vma', '.linux=0x2000000', '--add-section', '.initrd=/var/tmp/mkosi-h5nk8fuh/root/efi/ab6508a14b584b6e8830ecd72c78df7a/6.5.0-0.rc2.20230719gitccff6d117d8d.18.fc39.x86_64/initrd', '--change-section-vma', '.initrd=0x3000000', '/var/tmp/mkosi-h5nk8fuh/root/lib/systemd/boot/efi/linuxx64.efi.stub', '/var/tmp/mkosi-h5nk8fuh/root/efi/EFI/Linux/fedora_test-6.5.0-0.rc2.20230719gitccff6d117d8d.18.fc39.x86_64.efi']' returned non-zero exit status 1.
                                                     
```

Looks similar to #1155

**Comment by DaanDeMeyer** [comment]
Please run mkosi from git, the distro provided packages are too old until we do another release.

**Comment by shvchk** [comment]
Done, but now it seems to require systemd 253+

```
systemd-repart: unrecognized option '--offline=yes'
‣ "systemd-repart --empty=allow --size=auto --dry-run=no --json=pretty --no-pager --offline=yes --root /home/shevchuk/current/projects/tmp/mkosi-test/fedora/.mkosi.tmpy5h589jq/root /home/shevchuk/current/projects/tmp/mkosi-test/fedora/.mkosi.tmpy5h589jq/staging/image.raw --empty=create --defer-partitions esp,xbootldr --definitions /home/shevchuk/current/projects/tmp/mkosi-test/fedora/.mkosi.tmpy5h589jq/repart-definitions" returned non-zero exit code 1.
```

Ubuntu is now on systemd 252, so... out of options on host, I suppose 🤷‍♂️ will probably have to use a VM

**Comment by DaanDeMeyer** [comment]
> Ubuntu is now on systemd 252, so... out of options on host, I suppose man_shrugging will probably have to use a VM

We have --tools-tree for this issue now. For building directory images, you only need a package manager and bubblewrap. You can then use that directory image with --tools-tree= to build another image using only tools from that directory image. So you could build a tools tree image using debian experimental which has systemd-v254-rc2 which will work.

I need to document this somewhere along with the list of packages to install in the tools tree.
