### ISSUE TITLE
mkosi crashes if no package is provided at all (Arch)

### ISSUE THREAD

**Issue by fthiery** [systemd/mkosi#171]
Regression induced by NetworkManager support (#153):

```
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3071, in <module>
    main()
  File "/usr/bin/mkosi", line 3067, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3019, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/bin/mkosi", line 2869, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "/usr/bin/mkosi", line 1287, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1182, in install_arch
    if not "networkmanager" in args.packages:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by fthiery** [comment]
See https://github.com/systemd/mkosi/pull/170 for the PR
