### ISSUE TITLE
Missing packages when building Debian image resulting in failure.

### ISSUE THREAD

**Issue by VasilisMylonas** [systemd/mkosi#1798]
Creating a Debian image with the following config:

```
# mkosi.default
[Distribution]
Distribution=debian

[Output]
Format=gpt_squashfs
Bootable=yes

[Content]
Password=123
```

yields the following error:

```
Processing triggers for libc-bin (2.37-7) ...
Processing triggers for dracut (059-4) ...
Failed to enable unit, unit systemd-resolved.service does not exist.
‣  (Unmounting Package Cache)
‣  (Unmounting image)
‣  (Detaching /dev/loop0)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 32, in <module>
    main()
  File "/usr/lib/python3/dist-packages/mkosi/__main__.py", line 26, in main
    run_verb(a)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7809, in run_verb
    manifest = build_stuff(args)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 7227, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 6965, in build_image
    install_distribution(args, root, do_run_build_script, cached_tree)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 3111, in install_distribution
    install[args.distribution](args, root, do_run_build_script)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2760, in install_debian
    install_debian_or_ubuntu(args, root, do_run_build_script=do_run_build_script)
  File "/usr/lib/python3/dist-packages/mkosi/__init__.py", line 2755, in install_debian_or_ubuntu
    run(["systemctl", "--root", root, "enable", "systemd-resolved"])
  File "/usr/lib/python3/dist-packages/mkosi/backend.py", line 699, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['systemctl', '--root', '/var/tmp/mkosi-6s86bqss/root', 'enable', 'systemd-resolved']' returned non-zero exit status 1.
```
It seems that systemd-resolved is never installed, yet mkosi tries to enable its services.

Adding `Packages=systemd-resolved` solves this problem but triggers failure later down the line during bootloader installation:

```
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-resolved.service → /lib/systemd/system/systemd-resolved.service.
Setting up binutils-x86-64-linux-gnu (2.41-4) ...
Setting up binutils (2.41-4) ...
Setting up linux-image-6.4.0-2-amd64 (6.4.4-3) ...
I: /vmlinuz.old is now a symlink to boot/vmlinuz-6.4.0-2-amd64
I: /vmlinuz is now a symlink to boot/vmlinuz-6.4.0-2-amd64
Setting up linux-image-amd64 (6.4.4-3) ...
Processing triggers for libc-bin (2.37-7) ...
Processing triggers for dracut (059-4) ...
‣  Unmounting Package Cache
‣  Installing boot loader…
execv(bootctl) failed: No such file or directory
‣ Error: Workspace command bootctl install returned non-zero exit code 1.
‣  (Unmounting image)
‣  (Detaching /dev/loop0)
```

Similarly it seems that systemd-boot is never installed yet mkosi runs bootctl.

With `Packages=systemd-resolved,systemd-boot` both problems seem to be resolved and the image is generated although the following warnings/errors are present in the output which may be of concern:

```
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/efi/EFI/BOOT/BOOTX64.EFI".
⚠️ Mount point '/efi' which backs the random seed file is world accessible, which is a security hole! ⚠️
⚠️ Random seed file '/efi/loader/.#bootctlrandom-seeddeba4ffe42d7698c' is world accessible, which is a security hole! ⚠️
Random seed file /efi/loader/random-seed successfully written (32 bytes).
/usr/bin/env: 'python3': No such file or directory
/usr/lib/kernel/install.d/60-ukify.install failed with exit status 127.
Setting up libdbus-1-3:amd64 (1.14.8-2) ...
```

mkosi version is 15.1 installed via pipx in Linux Mint 21.2

**Comment by VasilisMylonas** [comment]
It seems running with sudo was somehow using the apt installed version indeed. Running it with an absolute path still gives:

```
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
Processing triggers for libc-bin (2.37-7) ...
‣ A bootable image was requested but systemd-boot was not found at usr/lib/systemd/boot/efi
```

So systemd-boot is still not installed but this could be intentional?

**Comment by DaanDeMeyer** [comment]
Running with sudo means it will only look in /usr for programs and ignore your PATH. 

Yes this is intentional, there have been a great deal of breaking changes in mkosi v15. Please read NEWS and the documentation for more information. docs/bootable.md has information on how to generate a bootable image now.
