### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'output_bmap'

### ISSUE THREAD

**Issue by falstaff84** [systemd/mkosi#194]
With 756187d483840ab68be4d89f692cdfc665643c65 I get the following stacktrace on Arch Linux

        ...
       ‣ Creating BMAP file...
        Traceback (most recent call last):
          File "/usr/bin/mkosi", line 3304, in <module>
            main()
          File "/usr/bin/mkosi", line 3297, in main
            build_stuff(args)
          File "/usr/bin/mkosi", line 3231, in build_stuff
            bmap = calculate_bmap(args, raw)
          File "/usr/bin/mkosi", line 1995, in calculate_bmap
            dir=os.path.dirname(args.output_bmap))
        AttributeError: 'Namespace' object has no attribute 'output_bmap'

**Comment by lucasdemarchi** [comment]
argh... somehow I forgot a check for when people don't enable bmap, sorry. I'll fix it.
