### ISSUE TITLE
`--force` is incompatible with `ToolsTree=default` and building multiple images

### ISSUE THREAD

**Issue by richardmaw-codethink** [systemd/mkosi#2280]
When `ToolsTree=default` is provided, an extra build step is added to each image.

This step checks for if it needs to be rebuilt in https://github.com/systemd/mkosi/blob/4a4b8bd7853ba25b1f39506d5c0760f97f5720f0/mkosi/__init__.py#L3440

This works fine the first time you build the images, because the extra step for each image checks whether the tools tree needs to be built.

Unfortunately, when `--force` is passed because you need to rebuild an image, it fails, because the tools tree rebuild step has been added to every image, and when `--force` is passed it bypasses the check for whether the image already exists, and the tools tree build step isn't idempotent, so it fails when it tries to rename the built tools tree into the output directory.

This produces an error that looks like:

```
richardmaw@skullthought:~/workspace/sy002/systemd-wt$ meson test -C build/ --suite integration-tests
ninja: no work to do.
ninja: Entering directory `/home/richardmaw/workspace/sy002/systemd-wt/build'
[0/1] Generating system_mkosi with a custom command
+ output=system
+ mkosi -C .. --image=system --without-tests -f build
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Removing output files…
‣ Building fedora-tools image
‣  Copying cached trees
‣  Generating system users
‣  Applying presets…
Removed "/home/richardmaw/.cache/mkosi-workspace951fiuri/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service".
Created symlink /home/richardmaw/.cache/mkosi-workspace951fiuri/root/etc/systemd/system/timers.target.wants/fstrim.timer → /lib/systemd/system/fstrim.timer.
Created symlink /home/richardmaw/.cache/mkosi-workspace951fiuri/root/etc/systemd/system/multi-user.target.wants/machines.target → /lib/systemd/system/machines.target.
Created symlink /home/richardmaw/.cache/mkosi-workspace951fiuri/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service → /lib/systemd/system/systemd-homed-activate.service.
‣  Generating hardware database
‣  /home/richardmaw/workspace/sy002/systemd-wt/mkosi.output/fedora-tools size is 855.4M.
‣ Building base image
‣  Copying cached trees
‣  Running build script /home/richardmaw/workspace/sy002/systemd-wt/mkosi.images/base/mkosi.build.chroot…
+ ninja -C /work/build
ninja: Entering directory `/work/build'
[1/688] Generating version.h with a custom command
+ meson install -C /work/build --quiet --no-rebuild --only-changed
‣  Copying in extra file trees…
‣  Generating system users
‣  Applying presets…
Created symlink /home/richardmaw/.cache/mkosi-workspacek8ue3hey/root/etc/systemd/system/timers.target.wants/fstrim.timer → /usr/lib/systemd/system/fstrim.timer.
‣  Generating hardware database
No hwdb files found, skipping.
‣  /home/richardmaw/workspace/sy002/systemd-wt/mkosi.output/base size is 142.6M.
‣ Building fedora-tools image
‣  Copying cached trees
‣  Generating system users
‣  Applying presets…
Removed "/home/richardmaw/.cache/mkosi-workspacepoa5wnqc/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service".
Created symlink /home/richardmaw/.cache/mkosi-workspacepoa5wnqc/root/etc/systemd/system/timers.target.wants/fstrim.timer → /lib/systemd/system/fstrim.timer.
Created symlink /home/richardmaw/.cache/mkosi-workspacepoa5wnqc/root/etc/systemd/system/multi-user.target.wants/machines.target → /lib/systemd/system/machines.target.
Created symlink /home/richardmaw/.cache/mkosi-workspacepoa5wnqc/root/etc/systemd/system/systemd-homed.service.wants/systemd-homed-activate.service → /lib/systemd/system/systemd-homed-activate.service.
‣  Generating hardware database
Traceback (most recent call last):
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/run.py", line 162, in uncaught_exception_handler
    yield
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/run.py", line 203, in fork_and_wait
    target()
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/__init__.py", line 3469, in <lambda>
    fork_and_wait(lambda: run_build(args, tools)) # pyright: ignore
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/__init__.py", line 3384, in run_build
    build_image(args, config)
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/__init__.py", line 2890, in build_image
    finalize_staging(context)
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/__init__.py", line 2730, in finalize_staging
    move_tree(
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/tree.py", line 153, in move_tree
    raise e
  File "/home/richardmaw/workspace/sy002/mkosi/mkosi/tree.py", line 150, in move_tree
    src.rename(dst)
  File "/usr/lib/python3.11/pathlib.py", line 1176, in rename
    os.rename(self, target)
FileExistsError: [Errno 17] File exists: '/home/richardmaw/.cache/mkosi-workspacepoa5wnqc/staging/fedora-tools' -> '/home/richardmaw/workspace/sy002/systemd-wt/mkosi.output/fedora-tools'
FAILED: system 
```

**Comment by richardmaw-codethink** [comment]
Thanks, this fix solved my problem.
