### ISSUE TITLE
TypeError raised when building cache

### ISSUE THREAD

**Issue by thedrow** [systemd/mkosi#258]
I'm running `mkosi -i` and I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 2904, in <module>
    main()
  File "/usr/bin/mkosi", line 2900, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 2833, in build_stuff
    args.cache_pre_dev)
  File "/usr/bin/mkosi", line 1751, in save_cache
    os.chmod(raw, 0o666 & ~args.original_umask)
TypeError: chmod: path should be string, bytes, os.PathLike or integer, not NoneType
```

I installed mkosi from master.

**Comment by hishine6** [comment]
I am currently having the same problem. I understand that this issue happend 4 years ago, but if you remember... which path have you updated to solve this problem? Thank you in advance.

**Comment by thedrow** [comment]
I honestly don't recall.
