### ISSUE TITLE
Filenotfound error when building initrd from kernel-install

### ISSUE THREAD

**Issue by cvlc12** [systemd/mkosi#2904]
### mkosi commit the issue has been seen with

23.1

### Used host distribution

Arch

### Linux kernel version used

6.10.0-arch1-2

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

```FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/mkosi-workspace-014zw71p/root/etc/machine-id'```

While trying to build an initrd with the kernel-install plugin. It looks like the work folder is deleted in the step just before

### mkosi output

```sh
# kernel-install add 6.6.40-2-lts /lib/modules/6.6.40-2-lts/vmlinuz --verbose
layout=uki set via config
INITRD_GENERATOR (mkosi-initrd) set via config.
UKI_GENERATOR (ukify) set via config.
Loaded config.
Loading /etc/machine-info…
MACHINE_ID=982132008de649089768b8fa1887cbe1 set via /etc/machine-id.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Directory "/boot" is not the root of the file system.
Couldn't find an XBOOTLDR partition.
Using EFI System Partition at /efi as $BOOT_ROOT.
Using entry token: 982132008de649089768b8fa1887cbe1
kernel version (6.6.40-2-lts) set via command line.
kernel image file (/lib/modules/6.6.40-2-lts/vmlinuz) set via command line.
Using ENTRY_DIR=/efi/982132008de649089768b8fa1887cbe1/6.6.40-2-lts
Using plugins: 
  /usr/lib/kernel/install.d/50-depmod.install
  /usr/lib/kernel/install.d/50-mkinitcpio.install
  /usr/lib/kernel/install.d/50-mkosi.install
  /etc/kernel/install.d/55-lsinitcpio.install
  /usr/lib/kernel/install.d/60-ukify.install
  /usr/lib/kernel/install.d/90-loaderentry.install
  /usr/lib/kernel/install.d/90-uki-copy.install
  /usr/lib/kernel/install.d/91-sbctl.install
Plugin environment: 
  LC_COLLATE=C.UTF-8
  KERNEL_INSTALL_VERBOSE=1
  KERNEL_INSTALL_IMAGE_TYPE=pe
  KERNEL_INSTALL_MACHINE_ID=982132008de649089768b8fa1887cbe1
  KERNEL_INSTALL_ENTRY_TOKEN=982132008de649089768b8fa1887cbe1
  KERNEL_INSTALL_BOOT_ROOT=/efi
  KERNEL_INSTALL_LAYOUT=uki
  KERNEL_INSTALL_INITRD_GENERATOR=mkosi-initrd
  KERNEL_INSTALL_UKI_GENERATOR=ukify
  KERNEL_INSTALL_STAGING_AREA=/tmp/kernel-install.staging.0yxVe6
Plugin arguments: add 6.6.40-2-lts /efi/982132008de649089768b8fa1887cbe1/6.6.40-2-lts /lib/modules/6.6.40-2-lts/vmlinuz
Successfully forked off '(sd-exec-strv)' as PID 16816.
About to execute /usr/lib/kernel/install.d/50-depmod.install add 6.6.40-2-lts /efi/982132008de649089768b8fa1887cbe1/6.6.40-2-lts /lib/modules/6.6.40-2-lts/vmlinuz
Successfully forked off '(direxec)' as PID 16817.
+depmod -a 6.6.40-2-lts
/usr/lib/kernel/install.d/50-depmod.install succeeded.
About to execute /usr/lib/kernel/install.d/50-mkinitcpio.install add 6.6.40-2-lts /efi/982132008de649089768b8fa1887cbe1/6.6.40-2-lts /lib/modules/6.6.40-2-lts/vmlinuz
Successfully forked off '(direxec)' as PID 16818.
/usr/lib/kernel/install.d/50-mkinitcpio.install succeeded.
About to execute /usr/lib/kernel/install.d/50-mkosi.install add 6.6.40-2-lts /efi/982132008de649089768b8fa1887cbe1/6.6.40-2-lts /lib/modules/6.6.40-2-lts/vmlinuz
Successfully forked off '(direxec)' as PID 16819.
‣ Building uki
‣ + stat --file-system --format %T /var/tmp/mkosi-workspace-95oejgxc
‣ + btrfs subvolume create /var/tmp/mkosi-workspace-95oejgxc/root
Create subvolume '/var/tmp/mkosi-workspace-95oejgxc/root'
‣ Copying in package manager file trees…
‣ + cp --version
‣ + cp --recursive --no-dereference --preserve=mode,links --reflink=auto --copy-contents /tmp/tmpr0gylvqm /var/tmp/mkosi-workspace-95oejgxc/pkgmngr --keep-directory-symlink --no-target-directory
‣ + rm -rf -- /var/tmp/mkosi-workspace-95oejgxc
‣ + mount --make-rslave /
‣ + mount --rbind /etc /etc --options ro
‣ + mount --rbind /opt /opt --options ro
‣ + mount --rbind /boot /boot --options ro
‣ + mount --rbind /efi /efi --options ro
‣ + mount --rbind /media /media --options ro
‣ + mount --rbind /usr /usr --options ro
‣ Building default image
‣ + stat --file-system --format %T /var/tmp/mkosi-workspace-qa2wrowf
‣ + btrfs subvolume create /var/tmp/mkosi-workspace-qa2wrowf/root
Create subvolume '/var/tmp/mkosi-workspace-qa2wrowf/root'
‣  Copying in package manager file trees…
‣ + cp --version
‣ + cp --recursive --no-dereference --preserve=mode,links --reflink=auto --copy-contents /tmp/tmpr0gylvqm /var/tmp/mkosi-workspace-qa2wrowf/pkgmngr --keep-directory-symlink --no-target-directory
‣ Acquiring lock on /var/cache/pacman
‣ Acquired lock on /var/cache/pacman
‣ Acquiring lock on /var/lib/pacman
‣ Acquired lock on /var/lib/pacman
‣ + cp --version
‣ + cp --recursive --no-dereference --preserve=mode,links --reflink=auto --copy-contents /var/cache/pacman /var/tmp/mkosi-workspace-qa2wrowf/root/var/cache/pacman --keep-directory-symlink --no-target-directory
‣ + cp --version
‣ + cp --recursive --no-dereference --preserve=mode,links --reflink=auto --copy-contents /var/lib/pacman /var/tmp/mkosi-workspace-qa2wrowf/root/var/lib/pacman --keep-directory-symlink --no-target-directory
‣  Installing Arch
‣ + pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch x86_64 --color auto --noconfirm --sync --needed --assume-installed initramfs filesystem
warning: filesystem-2024.04.07-1 is up to date -- skipping
 there is nothing to do
‣ + rm -rf -- /var/tmp/mkosi-workspace-qa2wrowf
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 60, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 101, in fork_and_wait
    target(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 4625, in run_build
    build_image(Context(args, config, workspace=workspace, resources=resources))
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 3790, in build_image
    install_distribution(context)
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 153, in install_distribution
    (context.root / "etc/machine-id").write_text("uninitialized\n")
  File "/usr/lib/python3.12/pathlib.py", line 1047, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/mkosi-workspace-qa2wrowf/root/etc/machine-id'
‣ + tput cnorm
‣ + tput smam
‣ "mkosi --directory '' --format uki --output uki --workspace-dir=/var/tmp --package-cache-dir=/var --cache-only=metadata --output-dir /tmp/kernel-install.staging.0yxVe6 --extra-tree /usr/lib/modules/6.6.40-2-lts:/usr/lib/modules/6.6.40-2-lts --extra-tree=/usr/lib/firmware:/usr/lib/firmware '--kernel-modules-exclude=.*' --kernel-modules-include=host --include=mkosi-initrd --debug --include /etc/mkosi-initrd --package-manager-tree /tmp/tmpr0gylvqm" returned non-zero exit code 1.
/usr/lib/kernel/install.d/50-mkosi.install failed with exit status 1.
/usr/lib/kernel/install.d/50-mkosi.install failed with exit status 1.
(sd-exec-strv) failed with exit status 1.
```

**Comment by DaanDeMeyer** [comment]
@cvlc12 Should be fixed by the attached PR, can you give it a try?

**Comment by DaanDeMeyer** [comment]
@cvlc12 As the error says, is cpio installed on your system?

**Comment by DaanDeMeyer** [comment]
@cvlc12 Can you try https://github.com/systemd/mkosi/pull/2909?
