### ISSUE TITLE
Arch build failing during "kernel-install"

### ISSUE THREAD

**Issue by qjcg** [systemd/mkosi#293]
Building an Arch image is failing for me, with the "kernel-install" command returning exit status 1.

(Build host: up to date Arch system; got identical errors using both the [last mkosi release](https://github.com/systemd/mkosi/tree/v4) and the [latest HEAD](https://github.com/systemd/mkosi/tree/651a6b2b11e4760f76a1611b4046620ce2185f87)).

For example, running

```sh
sudo mkosi -d arch --bootable --root-size 4G build
```

produces the following build failure (with no image file being ouptut):

```sh
[...]
‣ Installing Arch Linux complete.
‣ Assigning hostname...
‣ Assigning hostname complete.
‣ Installing boot loader...
bind(/run/systemd/nspawn/notify) failed: Address already in use
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Unmounting image...
‣ Unmounting image complete.
‣ Detaching image file...
‣ Detaching image file complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4011, in <module>
    main()
  File "/usr/bin/mkosi", line 4001, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3846, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False, cleanup=True)
  File "/usr/bin/mkosi", line 3694, in build_image
    install_boot_loader(args, workspace.name, loopdev, cached)
  File "/usr/bin/mkosi", line 1964, in install_boot_loader
    install_boot_loader_arch(args, workspace, loopdev)
  File "/usr/bin/mkosi", line 1913, in install_boot_loader_arch
    run_workspace_command(args, workspace, "/usr/bin/kernel-install", "add", kernel_version, find_kernel_file(workspace_root, "/boot/vmlinuz-*"))
  File "/usr/bin/mkosi", line 1013, in run_workspace_command
    run(cmdline, check=True)
  File "/usr/bin/mkosi", line 72, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-nspawn', '--quiet', '--directory=/var/tmp/mkosi-kfwsvtws/root', '--uuid=6e0bdc33c6634433aa98ccf97dbea181', '--machine=mkosi-692d0495a37046fc8b382552a715055d', '--as-pid2', '--register=no', '--bind=/var/$
mp/mkosi-kfwsvtws/var-tmp:/var/tmp', '--setenv=SYSTEMD_OFFLINE=1', '--private-network', '--', '/usr/bin/kernel-install', 'add', '4.19.2-arch1-1-ARCH', '/boot/vmlinuz-linux']' returned non-zero exit status 1.
```

**Comment by fthiery** [comment]
Arch is already using 239.300-2, which is the last stable one according to https://github.com/systemd/systemd/releases

```$ systemctl --version
systemd 239
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid```

I have the issue too

**Comment by fthiery** [comment]
Might be unrelated but i also see:
```
(10/15) Creating temporary files...
error: command failed to execute correctly
```

**Comment by fthiery** [comment]
Here is a reproduction mkosi.default file

```
[Distribution]
Distribution=arch
Mirror=http://mir.archlinux.fr

[Output]
Format=raw_gpt
Bootable=yes
Hostname=test
Output=test-image.raw
```

**Comment by lucasdemarchi** [comment]
See https://github.com/systemd/systemd-stable/pull/12

**Comment by qjcg** [comment]
Thanks for the pointer, @lucasdemarchi.

Since the issue's been resolved upstream but not yet in Arch's systemd package (at the time of writing, release 239.300-2), I rebuilt systemd via ABS using the most recent [v239-stable commit hash](https://github.com/systemd/systemd-stable/tree/v239-stable) to work around it:

```
asp export systemd
cd systemd
sed -i 's/^_commit.*/_commit=6b4878d667737b523ea251f2d8abde9748bb295e/' PKGBUILD
makepkg -s
sudo pacman -U *.pkg.tar.xz
```

After the above, mkosi builds are working for me again.

**Comment by fthiery** [comment]
Perfect, thanks. I also confirm the fix.

**Comment by fthiery** [comment]
FYI Arch just pushed stable systemd-239.303 update, the workaround isn't necessary anymore.
