### ISSUE TITLE
No such file or directory: `$workspace/root/var/cache/libdnf5`

### ISSUE THREAD

**Issue by msanft** [systemd/mkosi#2972]
### mkosi commit the issue has been seen with

main

### Used host distribution

NixOS Unstable

### Used target distribution

Fedora 40

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

`FileNotFoundError: [Errno 2] No such file or directory: '/home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root/var/cache/libdnf5'`

### Used mkosi config

```ini
[Distribution]
Distribution=fedora
Release=40
RepositoryKeyFetch=yes

[Output]
Format=tar
CompressOutput=false
Seed=b04a9a33-4559-4af4-8b38-9249cf933229

[Content]
SourceDateEpoch=0
Bootable=no
Packages=systemd
         systemd-boot
         dbus
         udev
         util-linux
         kernel
         kernel-core
         kernel-modules

# nvme / disk / udev tools
Packages=nvme-cli
         ec2-utils
         WALinuxAgent-udev
         google-compute-engine-guest-configs-udev # google_nvme_id
         device-mapper
         cryptsetup

# Containers
Packages=containerd
         containernetworking-plugins
         iptables-nft
         ethtool
         socat
         iproute-tc
         conntrack-tools
         podman

# Network
Packages=iproute
         dbus
         systemd-networkd
         systemd-resolved

# measured / secure boot
Packages=e2fsprogs
         sbsigntools
         efitools
         mokutil
         tpm2-tools

# selinux
Packages=selinux-policy
         selinux-policy-targeted

# tools
Packages=passwd
         nano
         nano-default-editor
         vim
         curl
         wget

RemoveFiles=/var/log
RemoveFiles=/var/cache
RemoveFiles=/etc/pki/ca-trust/extracted/java/cacerts
            /var/cache/ldconfig/aux-cache
RemoveFiles=/etc/issue
RemoveFiles=/etc/issue.net
```

### mkosi output

```sh
‣ Including configuration file /home/moritzs/dev/edgeless/constellation/image/system/mkosi.conf
‣ + timedatectl show -p Timezone --value
‣ Distribution of your host can't be detected or isn't a supported target. Defaulting to Distribution=custom.
‣ + timedatectl show -p Timezone --value
‣ + /nix/store/q7nb32cliimbnrcx6i5iml8c7ssqb3bj-systemd-256.2/bin/systemd-repart --version
‣ + rpm --eval '%{__plugindir}'
‣ Syncing package manager metadata for constellation image
‣ Acquiring lock on /home/moritzs/.cache/mkosi/fedora~40~x86-64/cache/libdnf5
‣ Acquired lock on /home/moritzs/.cache/mkosi/fedora~40~x86-64/cache/libdnf5
‣ Acquiring lock on /home/moritzs/.cache/mkosi/fedora~40~x86-64/lib/libdnf5
‣ Acquired lock on /home/moritzs/.cache/mkosi/fedora~40~x86-64/lib/libdnf5
‣ + dnf5 --assumeyes --best --releasever=40 --installroot=/buildroot --setopt=keepcache=1 --setopt=logdir=/var/log --setopt=cachedir=/var/cache/libdnf5 --setopt=persistdir=/var/lib/libdnf5 --setopt=install_weak_deps=0 --setopt=check_config_file_age=0 '--disable-plugin=*' --enable-plugin builddep --enable-plugin versionlock --setopt=debuglevel=10 --use-host-config --setopt=proxy_sslcacert=/proxy.cacert makecache
No matches were found for the following plugin name patterns while enabling libdnf plugins: builddep, versionlock
No matches were found for the following plugin name patterns while disabling libdnf plugins: *
Updating and loading repositories:
Repositories loaded.
Metadata cache created.
‣ + rm -rf -- /home/moritzs/.cache/mkosi/mkosi-workspace-vpm2r58_
‣ Building constellation image
‣  Copying in base trees…
‣   Extracting tar archive /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/image/base/lts.tar…
‣ + tar --extract --file /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/image/base/lts.tar --directory /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root --keep-directory-symlink --no-overwrite-dir --same-permissions --numeric-owner --same-order --acls --selinux --xattrs --force-local --exclude './dev/*' --exclude './proc/*' --exclude './sys/*' --exclude './tmp/*' --exclude './run/*' --exclude './var/tmp/*'
tar: SELinux support is not available
‣ Found repository metadata in /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root/var, not copying repository metadata
‣ + rpm --eval '%{__plugindir}'
‣ + bootctl --version
‣ + bootctl kernel-identify /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root/usr/lib/modules/6.6.30-100.constellation.fc40.x86_64/vmlinuz
‣  Running depmod for 6.6.30-100.constellation.fc40.x86_64
‣ + depmod --all 6.6.30-100.constellation.fc40.x86_64
‣  Copying in extra file trees…
‣   Extracting tar archive /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/upgrade-agent/cmd/upgrade-agent-package.tar…
‣ + tar --extract --file /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/upgrade-agent/cmd/upgrade-agent-package.tar --directory /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root --keep-directory-symlink --no-overwrite-dir --same-permissions --numeric-owner --same-order --acls --selinux --xattrs --force-local --exclude './dev/*' --exclude './proc/*' --exclude './sys/*' --exclude './tmp/*' --exclude './run/*' --exclude './var/tmp/*'
tar: SELinux support is not available
‣   Extracting tar archive /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/bootstrapper/cmd/bootstrapper/bootstrapper-package.tar…
‣ + tar --extract --file /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/bootstrapper/cmd/bootstrapper/bootstrapper-package.tar --directory /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root --keep-directory-symlink --no-overwrite-dir --same-permissions --numeric-owner --same-order --acls --selinux --xattrs --force-local --exclude './dev/*' --exclude './proc/*' --exclude './sys/*' --exclude './tmp/*' --exclude './run/*' --exclude './var/tmp/*'
tar: SELinux support is not available
‣   Extracting tar archive /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/measurement-reader/cmd/measurement-reader-package.tar…
‣ + tar --extract --file /home/moritzs/.cache/bazel/_bazel_moritzs/10842abbef6f2cb4a4b10e9499c5cb28/execroot/_main/bazel-out/k8-opt/bin/measurement-reader/cmd/measurement-reader-package.tar --directory /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root --keep-directory-symlink --no-overwrite-dir --same-permissions --numeric-owner --same-order --acls --selinux --xattrs --force-local --exclude './dev/*' --exclude './proc/*' --exclude './sys/*' --exclude './tmp/*' --exclude './run/*' --exclude './var/tmp/*'
tar: SELinux support is not available
‣  Running postinstall script /home/moritzs/dev/edgeless/constellation/image/system/mkosi.postinst…
‣ + /work/postinst final
‣ + rm -rf -- /home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem
Traceback (most recent call last):
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/run.py", line 63, in uncaught_exception_handler
    yield
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/run.py", line 104, in fork_and_wait
    target(*args, **kwargs)
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/__init__.py", line 4694, in run_build
    build_image(Context(args, config, workspace=workspace, resources=resources, package_dir=package_dir))
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/__init__.py", line 3953, in build_image
    run_postinst_scripts(context)
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/__init__.py", line 801, in run_postinst_scripts
    run(
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/run.py", line 151, in run
    with spawn(
  File "/nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/run.py", line 255, in spawn
    with sandbox as sbx:
  File "/nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/__init__.py", line 582, in script_maybe_chroot_sandbox
    *context.config.distribution.package_manager(context.config).mounts(context),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/installer/__init__.py", line 88, in mounts
    caches = context.config.distribution.package_manager(context.config).cache_subdirs(src)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/fal36ra25izw6yn1krz9r7izqvb7rb8m-mkosi-24.3/lib/python3.12/site-packages/mkosi/installer/dnf.py", line 28, in cache_subdirs
    return [
           ^
  File "/nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/pathlib.py", line 1056, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/moritzs/.cache/mkosi/mkosi-workspace-9faeztem/root/var/cache/libdnf5'
```

**Comment by behrmann** [comment]
Could you rerun this with debug logging and attach those logs as well?

**Comment by behrmann** [comment]
Also, are there any other scripts besides the postinst script?
