### ISSUE TITLE
sandbox fails when using mount shorthand for mounting file

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#3181]
### mkosi commit the issue has been seen with

main

### Used host distribution

Fedora 40

### Used target distribution

Arch

### Linux kernel version used

6.11.6-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Using the shorthand `BuildSources=file` (as opposed to `BuildSources=file:file`) leads to a crash in the sandbox script.
The file should either get mounted in the same way directories are, or mkosi should at least check beforehand it the path refers to a file and exit early because the current OSError is hard to understand.

### Used mkosi config

```ini
This repo with the following drop-in:

# mkosi.local.conf
[Build]
BuildSources=mkosi.local.conf # any file will do
```

### mkosi output

```sh
...
‣  Running prepare script /home/septatrix/Documents/programming/mkosi/mkosi.prepare…
Traceback (most recent call last):
  File "/home/septatrix/Documents/programming/mkosi/mkosi/sandbox.py", line 873, in <module>
  File "/home/septatrix/Documents/programming/mkosi/mkosi/sandbox.py", line 838, in main
  File "/home/septatrix/Documents/programming/mkosi/mkosi/sandbox.py", line 644, in execute
  File "/home/septatrix/Documents/programming/mkosi/mkosi/sandbox.py", line 123, in mount
  File "/home/septatrix/Documents/programming/mkosi/mkosi/sandbox.py", line 98, in oserror
OSError: [Errno 22] Invalid argument: 'newroot/work/src'
‣ "/work/prepare final" returned non-zero exit code 1.
```

**Comment by septatrix** [comment]
And it deadlocks qemu when using virtiofsd which I found out when using `RuntimeBuildSources=yes`

```
‣ virtiofsd cmdline: [PosixPath('/usr/libexec/virtiofsd'), '--shared-dir', '/work/home/septatrix/Documents/university/semester13/LKP/Lab/lab03/config-lkp', '--xattr', '--no-announce-submounts', '--sandbox=chroot', '--inode-file-handles=never', '--fd', '3']
[2024-11-12T13:55:57Z WARN  virtiofsd::limits] Failure when trying to set the limit to 1000000, the hard limit (524288) of open file descriptors is used instead.
[2024-11-12T13:55:57Z ERROR virtiofsd] Error entering sandbox: Chroot(Os { code: 20, kind: NotADirectory, message: "Not a directory" })
```
