### ISSUE TITLE
Failure when building inside container

### ISSUE THREAD

**Issue by shocklateboy92** [systemd/mkosi#3186]
### mkosi commit the issue has been seen with

a15a97da5a102414bdd461e92e9faabf899692cc

### Used host distribution

Arch Linux

### Used target distribution

Arch Linux

### Linux kernel version used

6.11.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Crashed with the provided output when building inside an ArchLinux distrobox (docker) container.

### Used mkosi config

```ini
The config in the systemd repo as of the following commit:
https://github.com/systemd/systemd/commit/9466fe014f6083825ed819fe17bf98f72baa3af9
```

### mkosi output

```sh
fernie@sisko ~/src/systemd (git)-[main] % ../mkosi/bin/mkosi --debug
‣ Loading configuration file /home/fernie/src/systemd/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.conf.d/05-tools/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.conf.d/05-tools/mkosi.conf.d/arch.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.conf.d/10-arch/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.conf.d/20-build.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/build/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/build/mkosi.conf.d/arch/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/exitrd/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/exitrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/exitrd/mkosi.conf.d/20-build.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/initrd/mkosi.conf.d/arch.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/initrd/mkosi.conf.d/build.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/minimal-0/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/minimal-1/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/minimal-base/mkosi.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/minimal-base/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /home/fernie/src/systemd/mkosi.images/minimal-base/mkosi.conf.d/20-build.conf
‣ /home/fernie/src/systemd/build/mkosi.cache/arch~20241020.0.271562~x86-64~build.cache does not exist, not reusing cached images
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ /home/fernie/src/systemd/build/mkosi.cache/arch~20241020.0.271562~x86-64~exitrd.cache does not exist, not reusing cached images
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ /home/fernie/src/systemd/build/mkosi.cache/arch~20241020.0.271562~x86-64~initrd.cache does not exist, not reusing cached images
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ /home/fernie/src/systemd/build/mkosi.cache/arch~20241020.0.271562~x86-64~minimal-base.cache does not exist, not reusing cached images
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ /home/fernie/src/systemd/build/mkosi.cache/arch~20241020.0.271562~x86-64.cache does not exist, not reusing cached images
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf
‣ Loading configuration file /tmp/tmp1gns0u7d/resources/mkosi-initrd/mkosi.conf.d/10-arch.conf
‣ + /usr/bin/systemd-repart --version
‣ Validating certificates and keys
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ + /usr/lib/systemd/systemd-keyutil validate --certificate /work/home/fernie/src/systemd/mkosi.crt --private-key /work/home/fernie/src/systemd/mkosi.key
‣ Syncing package manager metadata
‣ Acquiring lock on /home/fernie/.cache/mkosi/arch~20241020.0.271562~x86-64/cache/pacman
‣ Acquired lock on /home/fernie/.cache/mkosi/arch~20241020.0.271562~x86-64/cache/pacman
‣ Acquiring lock on /home/fernie/.cache/mkosi/arch~20241020.0.271562~x86-64/lib/pacman
‣ Acquired lock on /home/fernie/.cache/mkosi/arch~20241020.0.271562~x86-64/lib/pacman
‣ + pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch x86_64 --color auto --noconfirm --sync --refresh
Traceback (most recent call last):
  File "/home/fernie/src/mkosi/mkosi/sandbox.py", line 873, in <module>
  File "/home/fernie/src/mkosi/mkosi/sandbox.py", line 838, in main
  File "/home/fernie/src/mkosi/mkosi/sandbox.py", line 479, in execute
  File "/home/fernie/src/mkosi/mkosi/sandbox.py", line 295, in mount_rbind
  File "/home/fernie/src/mkosi/mkosi/sandbox.py", line 98, in oserror
FileNotFoundError: [Errno 2] No such file or directory: 'newroot/etc/resolv.conf'
‣ "/usr/bin/python3 -SI /home/fernie/src/mkosi/mkosi/sandbox.py --proc /proc --unsetenv TMPDIR --setenv SYSTEMD_OFFLINE 1 --ro-bind /usr /usr --symlink usr/bin /bin --symlink usr/bin /sbin --symlink usr/lib /lib --symlink usr/lib /lib64 --ro-bind /etc/ld.so.cache /etc/ld.so.cache --dir /var/tmp --dir /var/log --unshare-ipc --ro-bind /home/fernie/src/mkosi/mkosi/sandbox.py /sandbox.py --dev /dev --ro-bind /etc/resolv.conf /etc/resolv.conf --setenv PATH /usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin:/bin --ro-bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/sandbox/etc /etc --dir /opt --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/tmp/mkosi-var-tmp-3e4fd3cc58d245f1 /srv --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/tmp/mkosi-var-tmp-622c62e3519a4315 /media --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/tmp/mkosi-var-tmp-69de4e939c2d46f1 /mnt --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/tmp/mkosi-var-tmp-7c954393dfb041db /var --dir /run --dir /tmp --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/tmp/mkosi-var-tmp-d235a2356a474b6d /var/tmp --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root /buildroot --ro-bind /etc/ca-certificates /etc/ca-certificates --ro-bind /etc/pacman.d/gnupg /etc/pacman.d/gnupg --ro-bind /etc/ssl /etc/ssl --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/repository /repository --bind '/home/fernie/.cache/mkosi/arch~20241020.0.271562~x86-64/cache/pacman' /var/cache/pacman --bind '/home/fernie/.cache/mkosi/arch~20241020.0.271562~x86-64/lib/pacman' /var/lib/pacman --ro-bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/repository /var/cache/pacman/mkosi --bind /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root/var/lib/pacman/local /var/lib/pacman/local --become-root --suppress-chown --ro-bind-try /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root/etc/machine-id /buildroot/etc/machine-id --ro-bind-try /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root/etc/passwd /etc/passwd --ro-bind-try /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root/etc/group /etc/group --ro-bind-try /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root/etc/shadow /etc/shadow --ro-bind-try /home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt/root/etc/gshadow /etc/gshadow --ro-bind /etc/ca-certificates/extracted/tls-ca-bundle.pem /proxy.cacert -- pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch x86_64 --color auto --noconfirm --sync --refresh" returned non-zero exit code 1.
‣ + rm -rf -- /work/home/fernie/.cache/mkosi/mkosi-workspace-9sxv41tt
‣ + tput cnorm
‣ + tput smam
Traceback (most recent call last):
  File "/home/fernie/src/mkosi/mkosi/run.py", line 62, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/fernie/src/mkosi/mkosi/__main__.py", line 36, in main
    run_verb(args, images, resources=resources)
  File "/home/fernie/src/mkosi/mkosi/__init__.py", line 4763, in run_verb
    sync_repository_metadata(args, images, resources=resources, dst=Path(metadata_dir))
  File "/home/fernie/src/mkosi/mkosi/__init__.py", line 4454, in sync_repository_metadata
    context.config.distribution.package_manager(context.config).sync(
  File "/home/fernie/src/mkosi/mkosi/installer/pacman.py", line 180, in sync
    cls.invoke(context, "--sync", ["--refresh", *(["--refresh"] if force else [])])
  File "/home/fernie/src/mkosi/mkosi/installer/pacman.py", line 171, in invoke
    return run(
           ^^^^
  File "/home/fernie/src/mkosi/mkosi/run.py", line 150, in run
    with spawn(
         ^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/fernie/src/mkosi/mkosi/run.py", line 295, in spawn
    raise subprocess.CalledProcessError(returncode, cmdline)
subprocess.CalledProcessError: Command '['pacman', '--root=/buildroot', '--logfile=/dev/null', '--dbpath=/var/lib/pacman', '--cachedir=/var/cache/pacman/mkosi', '--cachedir=/var/cache/pacman/pkg', '--hookdir=/buildroot/etc/pacman.d/hooks', '--arch', 'x86_64', '--color', 'auto', '--noconfirm', '--sync', '--refresh']' returned non-zero exit status 1.
```

**Comment by DaanDeMeyer** [comment]
@shocklateboy92 Can you give me a reproducer with distrobox by any chance? I can't figure it out from just the logs unfortunately.

**Comment by DaanDeMeyer** [comment]
@kerneis-anssi This is expected, you have to make sure the keyring is up-to-date before invoking mkosi, unrelated to this issue.

**Comment by shocklateboy92** [comment]
Here is the output with `--debug-sandbox`

[debug-sandbox-output-stderr.txt](https://github.com/user-attachments/files/17779388/debug-sandbox-output-stderr.txt)
[debug-sandbox-output-stdout.txt](https://github.com/user-attachments/files/17779389/debug-sandbox-output-stdout.txt)

**Comment by shocklateboy92** [comment]
Hey, so the machine rebooted and I can no longer reproduce the issue even on the same distrobox.

I really appreciate the effort to understand the root cause, but I don't see that being feasible anymore :face_with_diagonal_mouth: 

Closing till I can find another way to reproduce the issue.
