### ISSUE TITLE
cannot build Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#322]
I'm trying to build a custom Ubuntu Trusty to be able to run an old software.

IIUC, mkosi requires `systemd-sysv` in the generated image, as debootstrap command [includes it by default](https://github.com/systemd/mkosi/blob/2ecf72d136929105692aaf454216d7d1ddf126d4/mkosi#L1577). But this package is not available in Ubuntu Trusty 14.04.

There's any workaround? `systemd-sysv` is present in xenial repository.

```
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://archive.ubuntu.com/ubuntu...
E: Couldn't find these debs: systemd-sysv
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3614, in <module>
    main()
  File "/usr/bin/mkosi", line 3604, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3463, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/bin/mkosi", line 3312, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "/usr/bin/mkosi", line 1545, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1334, in install_ubuntu
    install_debian_or_ubuntu(args, workspace, run_build_script, args.mirror)
  File "/usr/bin/mkosi", line 1276, in install_debian_or_ubuntu
    run(cmdline, check=True)
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--merged-usr', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', 'trusty', '/home/fede/src/LilyDev/mkosi/.mkosi-ymnbhwvk/root', 'http://archive.ubuntu.com/ubuntu']' returned non-zero exit status 1.

```

**Comment by fedelibre** [comment]
Nevermind, I think I can use Xenial. `systemd-sysv` is in the security repository:

```
[Distribution]
Distribution=ubuntu
Release=xenial
Repositories=main security universe
```
