### ISSUE TITLE
Issues with unprivileged userns disabled

### ISSUE THREAD

**Issue by bjackman** [systemd/mkosi#3265]
### mkosi commit the issue has been seen with

c4bbf3b71a3e2cf947995caedf10f69da3c4957a

### Used host distribution

Ubuntu 24.04.1 LTS

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

[Recent Ubuntu versions](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces) have an AppArmor policy to disable creation of unprivileged user namespaces. 

This is extremely annoying but unfortunately it's a pretty sensible policy given the current state of the kernel, I expect other general-purpose distros will do the same if they haven't already. 

For AppArmor specifically you can disable the restriction system-wide with:

```sh
sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```

Or you can create a profile for the binary:

```
❯❯  cat > /etc/apparmor.d/mkosi 
abi <abi/4.0>,
include <tunables/global>

# REPLACE THE PATH to point to where the binary is
profile mkosi /home/brendan/.local/share/pipx/venvs/mkosi/bin/mkosi flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/mkosi>
}
❯❯  sudo systemctl reload apparmor
```

There is also a kernel patch floating around that does this with a sysctl separate from any LSM framework, in that case you remove the restriction system-wide with:

```
sudo sysctl -w kernel.unprivileged_userns_clone=1
```

(Note this has the opposite polarity of Ubuntu's AppArmor sysctl).

I dunno if other LSMs have something like Ubuntu's AppArmor thing. I assume they will because globally disabling unpriv userns must break a lot of useful stuff.

I wonder if there's any good fix for this? I guess if there are distro packages of mkosi they can just add the LSM profile where that's a possibility. For people installing from source.. I guess it just has to be docs? Maybe mkosi could spit out a suggested LSM config based on your distro and the path of its binary?

**Comment by bjackman** [comment]
For searchability, here's what the error looks like with the AppArmor restriction- `unshare` returns `-EPERM`:

```
❯❯  mkosi -f
‣ Validating certificates and keys
‣ Syncing package manager metadata
Traceback (most recent call last):
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 886, in <module>
    main()
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 802, in main
    userns = acquire_privileges(become_root=become_root)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 360, in acquire_privileges
    become_user(0, 0)
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 344, in become_user
    unshare(CLONE_NEWUSER)
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 103, in unshare
    oserror()
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 98, in oserror
    raise OSError(ctypes.get_errno(), os.strerror(ctypes.get_errno()), filename or None)
PermissionError: [Errno 13] Permission denied
‣ "apt-get -o APT::Architecture=amd64 -o APT::Architectures=amd64 -o APT::Install-Recommends=false -o APT::Immediate-Configure=off -o APT::Get::Assume-Yes=true -o APT::Get::AutomaticRemove=true -o APT::Get::Allow-Change-Held-Packages=true -o APT::Get::Allow-Remove-Essential=true -o APT::Sandbox::User=root -o Acquire::AllowReleaseInfoChange=true -o Acquire::Check-Valid-Until=false -o Dir::Cache=/var/cache/apt -o Dir::State=/var/lib/apt -o Dir::Log=/var/log/apt -o Dir::State::Status=/buildroot/var/lib/dpkg/status -o Dir::Bin::DPkg=/usr/bin/dpkg -o Debug::NoLocking=true -o DPkg::Options::=--root=/buildroot -o DPkg::Options::=--force-unsafe-io -o DPkg::Options::=--force-architecture -o DPkg::Options::=--force-depends -o DPkg::Options::=--no-debsig -o DPkg::Use-Pty=false -o DPkg::Install::Recursive::Minimum=1000 -o pkgCacheGen::ForceEssential=, update" returned non-zero exit code 1.
Traceback (most recent call last):
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 886, in <module>
    main()
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 802, in main
    userns = acquire_privileges(become_root=become_root)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 362, in acquire_privileges
    become_user(os.getuid(), os.getgid())
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 344, in become_user
    unshare(CLONE_NEWUSER)
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 103, in unshare
    oserror()
  File "/home/brendan/.local/share/pipx/venvs/mkosi/lib/python3.12/site-packages/mkosi/sandbox.py", line 98, in oserror
    raise OSError(ctypes.get_errno(), os.strerror(ctypes.get_errno()), filename or None)
PermissionError: [Errno 13] Permission denied
‣ "rm -rf -- /work/home/brendan/.cache/mkosi/mkosi-workspace-or4sdb7n" returned non-zero exit code 1.
```

**Comment by bjackman** [comment]
PS I didn't know anything about configuring AppArmor until 10 minutes ago, that profile I created might be a bit silly (e.g. I dunno what ` flags=(unconfined)` does).
