### ISSUE TITLE
honour $TMPDIR

### ISSUE THREAD

**Issue by shibumi** [systemd/mkosi#332]
Hi,
I am currently building images on a very small VM with maybe 1-2GB of RAM. On default all images will be build in `/var/run` that is equal to `tmpfs`. I can understand that you want to speed up the process with using `tmpfs`, but I would like to have a parameter to build it on my local disk. It should be at least configurable

**Comment by poettering** [comment]
hmm? we use /var/run? that directory is just a legacy alias for /run. mkosi uses neither to store large data. What it does use is /var/tmp, which is generally backed by real storage. Also see this:

https://systemd.io/TEMPORARY_DIRECTORIES

mkosi should probably honour $TMPDIR, but still, /var/tmp is definitely the right place for what it is doing, if $TMPDIR is not set.

**Comment by shibumi** [comment]
The actual error I run into is this one:
```
error: Partition /var/tmp/mkosi-c4o4zcnk/root too full: 279151 blocks needed, 230251 blocks free
error: not enough free disk space
error: failed to commit transaction (not enough free disk space)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Unmounting image...
‣ Unmounting image complete.
‣ Detaching image file...
‣ Detaching image file complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3614, in <module>
    main()
  File "/usr/bin/mkosi", line 3604, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3463, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/bin/mkosi", line 3312, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "/usr/bin/mkosi", line 1545, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1430, in install_arch
    run(cmdline, check=True)
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pacstrap', '-C', '/var/tmp/mkosi-c4o4zcnk/pacman.conf', '-d', '/var/tmp/mkosi-c4o4zcnk/root', 'texinfo', 'sed', 'sysfsutils', 'iputils', 'pciutils', 'gettext', 'pacman', 'linux', 'logrotate', 'linux-firmware', 'vi', 'which', 'less', 'perl', 'tar', 'grep', 'findutils', 'inetutils', 'util-linux', 'psmisc', 'file', 'procps-ng', 'shadow', 'coreutils', 'cryptsetup', 'gawk', 'glibc', 'nano', 'gzip', 'systemd-sysvcompat', 'licenses', 'filesystem', 'usbutils', 'bzip2', 'e2fsprogs', 'gcc-libs', 'bash', 'iproute2', 's-nail', 'diffutils']' returned non-zero exit status 1.
```

Ok, I thought that `/var/tmp` is tmpfs backed. Nevermind looks like I need to increase storage on my machine.

**Comment by poettering** [comment]
Let's leave the issue open. Honouring TMPDIR if it is set is definitely a good idea
