### ISSUE TITLE
mkosi fails to build debian under a musl based host

### ISSUE THREAD

**Issue by miasma** [systemd/mkosi#362]
I'm trying to build Debian under Alpine Linux. Alpine provides debootstrap, but requires one to explicitly state the architecture: `--arch amd64`. Otherwise one faces this error:
```
E: Invalid Release file, no entry for main/binary-musl-linux-amd64/Packages
```
This applies to all musl based distros, afaik. This is obviously a bug in debootstrap, but it can't be avoided since mkosi won't let one to override the architecture when using debootstrap. The override only works for dnf and some other backends.

mkosi allows specifying architecture with `--architecture <foo>` but this information is not passed to debootstrap. The relevant messages depicting the issue provided here:
```
# ./mkosi -d debian -r stable --bootable no --architecture x86_64 --format directory -O image --password root
...
‣ Installing Debian...
I: Retrieving InRelease 
I: Checking Release signature
I: Valid Release signature (key id 6D33866EDD8FFA41C0143AEDDCC9EFBF77E11517)
E: Invalid Release file, no entry for main/binary-musl-linux-amd64/Packages
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Unmounting image...
‣ Unmounting image complete.
Traceback (most recent call last):
  File "./mkosi", line 4628, in <module>
    main()
  File "./mkosi", line 4624, in main
    run_verb(a)
  File "./mkosi", line 4599, in run_verb
    build_stuff(args)
  File "./mkosi", line 4425, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "./mkosi", line 4246, in build_image
    do_run_build_script=do_run_build_script, cached=cached)
  File "./mkosi", line 2048, in install_distribution
    install[args.distribution](args, workspace, do_run_build_script)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "./mkosi", line 1760, in install_debian
    install_debian_or_ubuntu(args, workspace, do_run_build_script=do_run_build_script, mirror=args.mirror)
  File "./mkosi", line 1681, in install_debian_or_ubuntu
    run(cmdline, check=True)
  File "./mkosi", line 76, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', '--merged-usr', 'stable', '/mkosi/image/.mkosi-19qxh2if/root', 'http://deb.debian.org/debian']' returned non-zero exit status 1.
```
When invoking debootstrap directly:
```
# debootstrap stable /foo http://deb.debian.org/debian
I: Checking Release signature
I: Valid Release signature (key id 6D33866EDD8FFA41C0143AEDDCC9EFBF77E11517)
E: Invalid Release file, no entry for main/binary-musl-linux-amd64/Packages
```
And with the workaround:
```
# debootstrap --arch arm64 stable /foo http://deb.debian.org/debian
I: Checking Release signature
I: Valid Release signature (key id 6D33866EDD8FFA41C0143AEDDCC9EFBF77E11517)
I: Retrieving Packages 
I: Validating Packages 
```

**Comment by behrmann** [comment]
That seems like a straightforward fix. Is 4d88232bb4c91063978e934c9a7f6123f64b8bba enough for this to work for you?

**Comment by miasma** [comment]
Unfortunately no, debootstrap wants the string 'arm64', not 'x86_64'. Otherwise it would work.

**Comment by behrmann** [comment]
I see. I'll guess a straight forward solution would be to add a dictionary with mappings from architecture names in the Red Hat world to the Debian world. I'll hook that up tomorrow.

**Comment by behrmann** [comment]
@miasma Sorry for the delay, my machine died on me unexpectedly. Would this work a7de6b877f61cf71a9b0a6065b8eeeacbeb2979d work for you?

**Comment by miasma** [comment]
> @miasma Sorry for the delay, my machine died on me unexpectedly. Would this work [a7de6b8](https://github.com/systemd/mkosi/commit/a7de6b877f61cf71a9b0a6065b8eeeacbeb2979d) work for you?

Yes, thanks. It works now.
