### ISSUE TITLE
Unable to make bootable Arch Linux image with 'bios' boot protocol

### ISSUE THREAD

**Issue by craftyguy** [systemd/mkosi#380]
I'm unable to build a bootable (using --bootable flag) Arch Linux image for legacy/bios boot. The system I am trying to build this on is Arch Linux.

The cmdline to reproduce:
```
$ mkosi -d arch --boot-protocols bios --bootable
```

Relevant output:

```
‣ Installing boot loader...
Failed to create /dev/console symlink: File exists
Failed to setup /dev/console: File exists
Child died too early.
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Unmounting image...
‣ Unmounting image complete.
‣ Detaching image file...
‣ Detaching image file complete.
Traceback (most recent call last):
  File "/home/clayton/src/mkosi/mkosi", line 4762, in <module>
    main()
  File "/home/clayton/src/mkosi/mkosi", line 4758, in main
    run_verb(a)
  File "/home/clayton/src/mkosi/mkosi", line 4733, in run_verb
    build_stuff(args)
  File "/home/clayton/src/mkosi/mkosi", line 4558, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "/home/clayton/src/mkosi/mkosi", line 4376, in build_image
    install_boot_loader(args, workspace.name, loopdev, cached)
  File "/home/clayton/src/mkosi/mkosi", line 2380, in install_boot_loader
    install_boot_loader_arch(args, workspace, loopdev)
  File "/home/clayton/src/mkosi/mkosi", line 2314, in install_boot_loader_arch
    install_grub(args, workspace, loopdev, "grub")
  File "/home/clayton/src/mkosi/mkosi", line 2291, in install_grub
    loopdev, nspawn_params=nspawn_params)
  File "/home/clayton/src/mkosi/mkosi", line 1208, in run_workspace_command
    run(cmdline, check=True)
  File "/home/clayton/src/mkosi/mkosi", line 76, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-nspawn', '--quiet', '--directory=/var/tmp/mkosi-pk8vaiym/root', '--uuid=775e253819374c5bbd1c8f4e416e8070', '--machine=mkosi-f6cdc81ffa014f0ea6dc92d10724a784', '--as-pid2', '--register=no', '--bind=/var/tmp/mkosi-pk8vaiym/var-tmp:/var/tmp', '--setenv=SYSTEMD_OFFLINE=1', '--private-network', '--bind-ro=/dev', '--property=DeviceAllow=/dev/loop1', '--property=DeviceAllow=/dev/loop1p2', '--', 'grub-install', '--modules=ext2 part_gpt', '--target=i386-pc', '/dev/loop1']' returned non-zero exit status 1.
/tmp/mkosi
```

**Comment by craftyguy** [comment]
The failure is caused by passing `--bind=/dev` to npawn in `install_grub`:

```
 nspawn_params = [
   "--bind=/dev",
   "--property=DeviceAllow=" + loopdev,
]
```

**Comment by craftyguy** [comment]
Looks like this patch to systemd tries to create a symlink for `/dev/console`, which already exists because of the mount bind to `/dev` on the host: https://github.com/systemd/systemd/commit/3acc84ebd9aebe8cf1771b42644ebbfbecdfaa37
