### ISSUE TITLE
Arch linux base package no longer can generate a list

### ISSUE THREAD

**Issue by bwidawsk** [systemd/mkosi#418]
Currently, mkosi generates a list of base packages  using `pacman -Sqg base`. As of October 2019 (https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/), you cannot get a package list with `pacman -Sqg base` because it changed from being a group, to being a metapackage The closest thing (I think) would be to get the list in the "Depends On" section of `pacman -Si base`.

Note the failure because pacman -Sqg returns non-zero.
```
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4539, in <module>
    main()
  File "/usr/bin/mkosi", line 4535, in main
    run_verb(args)
  File "/usr/bin/mkosi", line 4507, in run_verb
    build_stuff(args)
  File "/usr/bin/mkosi", line 4333, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "/usr/bin/mkosi", line 4153, in build_image
    install_distribution(args, workspace.name,
  File "/usr/bin/mkosi", line 1987, in install_distribution
    install[args.distribution](args, workspace, do_run_build_script)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1790, in install_arch
    c = run_pacman(["-Sqg", "base"], stdout=PIPE, universal_newlines=True)
  File "/usr/bin/mkosi", line 1768, in run_pacman
    return run(cmdline + args, **kwargs, check=True)
  File "/usr/bin/mkosi", line 69, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pacman', '--noconfirm', '--color', 'never', '--config', '/var/tmp/mkosi-y5938yw1/pacman.conf', '-Sqg', 'base']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.8/weakref.py", line 642, in _exitfunc
    f()
  File "/usr/lib/python3.8/weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.8/tempfile.py", line 818, in _cleanup
    cls._rmtree(name)
  File "/usr/lib/python3.8/tempfile.py", line 814, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'root'
```

**Comment by bwidawsk** [comment]
@lucasdemarchi pointed out to me this is fixed in upstream, but not in anything"packaged".  Not sure if that means a release should be cut, or the AUR package needs updating.

**Comment by lucasdemarchi** [comment]
while there is no release, I guess arch could carry that patch downstream in its package
