### ISSUE TITLE
Fail to create squashfs [gpt or raw] root partition not created if --bootable

### ISSUE THREAD

**Issue by potens1** [systemd/mkosi#423]
Hello,

I don't know if it not something desirable (having squasfs image and bootable) but it seem it is not possible to create a squashfs bootable image (the aim is create some usb stick with squashfs root)

I'm trying to run either the version packaged in Arch or 5c5ac550ecc48089df7226cce2eb0da4ba0e58b8 (last commit at the time of writing) and it always fail for gpt or raw squashfs.
example of output:
```
╰ sudo  python mkosi/mkosi/mkosi.py -b -d debian -r buster --password temp -t gpt_squashfs --package=btrfs-progs --debug run --cache cache -o toto 
‣ Processing default...
COMMANDS:
                  verb: build
               cmdline: 
DISTRIBUTION:
          Distribution: debian
               Release: buster
                Mirror: http://deb.debian.org/debian

OUTPUT:
         Output Format: gpt_squashfs
                Output: /mnt/blazing/mkosi/toto
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: yes
        FS Compression: yes
        XZ Compression: no
                 QCow2: no
            Encryption: no
                Verity: no
              Bootable: yes
   Kernel Command Line: rhgb quiet selinux=0 audit=0 rw
       UEFI SecureBoot: no
        Boot Protocols: uefi

PACKAGES:
              Packages: btrfs-progs
         Package Cache: /mnt/blazing/mkosi/cache
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /mnt/blazing/mkosi
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
      Skip final phase: no
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

PARTITIONS:
        Root Partition: (automatic)
        Swap Partition: (disabled)
                   ESP: 256.0M
    XBOOTLDR Partition: (disabled)
       /home Partition: (disabled)
        /srv Partition: (disabled)
        /var Partition: (disabled)
    /var/tmp Partition: (disabled)

VALIDATION:
              Checksum: no
                  Sign: no
               GPG Key: default
              Password: set

HOST CONFIGURATION:
    Extra search paths: none
‣ Detaching namespace...
+ mount --make-rslave /
‣ Detaching namespace complete.
‣ Setting up package cache...
‣ Setting up package cache /mnt/blazing/mkosi/cache complete.
‣ Setting up temporary workspace.
‣ Temporary workspace in /var/tmp/mkosi-o55h5q0e is now set up.
‣ Running second (final) stage...
‣ Creating partition table...
+ chattr +C /mnt/blazing/mkosi/.mkosi-tggipobb
****************************************
part table required
label: gpt
size=524288, type=c12a7328-f81f-11d2-ba4b-00a0c93ec93b, name="ESP System Partition"

****************************************
+ sfdisk --color=never /mnt/blazing/mkosi/.mkosi-tggipobb
Checking that no-one is using this disk right now ... OK

Disk /mnt/blazing/mkosi/.mkosi-tggipobb: 258 MiB, 270532608 bytes, 528384 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: BF030A6B-6275-D44A-9834-3F8B1E2C2091).
/mnt/blazing/mkosi/.mkosi-tggipobb1: Created a new partition 1 of type 'EFI System' and of size 256 MiB.
/mnt/blazing/mkosi/.mkosi-tggipobb2: Done.

New situation:
Disklabel type: gpt
Disk identifier: BF030A6B-6275-D44A-9834-3F8B1E2C2091

Device                              Start    End Sectors  Size Type
/mnt/blazing/mkosi/.mkosi-tggipobb1  2048 526335  524288  256M EFI System

The partition table has been altered.
Syncing disks.
+ sync
‣ Created partition table as /mnt/blazing/mkosi/.mkosi-tggipobb.
‣ Attaching image file...
+ losetup --find --show --partscan /mnt/blazing/mkosi/.mkosi-tggipobb
‣ Attached image file as /dev/loop6.
‣ Formatting ESP partition...
+ mkfs.fat -nEFI -F32 /dev/loop6p1
mkfs.fat 4.1 (2017-01-24)
‣ Formatting ESP partition complete.
‣ Mounting image...
+ mount --bind /var/tmp/mkosi-o55h5q0e/root /var/tmp/mkosi-o55h5q0e/root
+ mount -n /dev/loop6p1 /var/tmp/mkosi-o55h5q0e/root/efi ''
mount: bad usage
Try 'mount --help' for more information.
‣ Detaching image file...
+ losetup --detach /dev/loop6
‣ Detaching image file complete.
Traceback (most recent call last):
  File "mkosi/mkosi/mkosi.py", line 5040, in <module>
    main()
  File "mkosi/mkosi/mkosi.py", line 5034, in main
    run_verb(a)
  File "mkosi/mkosi/mkosi.py", line 5011, in run_verb
    build_stuff(args)
  File "mkosi/mkosi/mkosi.py", line 4835, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "mkosi/mkosi/mkosi.py", line 4633, in build_image
    with mount_image(args, workspace.name, loopdev, None if args.generated_root() else encrypted_root,
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "mkosi/mkosi/mkosi.py", line 1123, in mount_image
    mount_loop(args, partition(loopdev, args.esp_partno), os.path.join(root, "efi"))
  File "mkosi/mkosi/mkosi.py", line 1076, in mount_loop
    run(["mount", "-n", dev, where, options_arg], check=True)
  File "mkosi/mkosi/mkosi.py", line 90, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mount', '-n', '/dev/loop6p1', '/var/tmp/mkosi-o55h5q0e/root/efi', '']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.8/weakref.py", line 642, in _exitfunc
    f()
  File "/usr/lib/python3.8/weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.8/tempfile.py", line 818, in _cleanup
    cls._rmtree(name)
  File "/usr/lib/python3.8/tempfile.py", line 814, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'root'
```
the text between the ************ is what I added to trace a bit what's wrong.

So, it seems that, when not using `bootable`, the plain loop device is used to do the squashfs BUT when using `bootable` partition(s) are created on loop, but not the root one.

this is the interesting part when not using bootable:
```
‣ Attaching image file...
+ losetup --find --show --partscan /mnt/blazing/mkosi/.mkosi-mrjghlps
‣ Attached image file as /dev/loop6.
‣ Mounting image...
+ mount --bind /var/tmp/mkosi-wpy9tbd_/root /var/tmp/mkosi-wpy9tbd_/root
+ mount tmpfs -t tmpfs /var/tmp/mkosi-wpy9tbd_/root/run
+ mount tmpfs -t tmpfs /var/tmp/mkosi-wpy9tbd_/root/tmp
‣ Mounting image complete.
```

**Comment by potens1** [comment]
In fact, thinking again about that, I just found you have the same problem if you don't use bootable but you ask other partitions (/home, i.e)
So, it seems the problem appears as soon as you have squashfs and require another partition

**Comment by zigarrre** [comment]
I can confirm this issue for the current master (1d6d137). Minimum way to reproduce is just (in an empty directory):
```
sudo mkosi -b -t gpt_squashfs
```
Running this I get the same behaviour/exception as @potens1.
