### ISSUE TITLE
RFE: Support extra repositories

### ISSUE THREAD

**Issue by potens1** [systemd/mkosi#430]
Hello,
when trying to add more repositories to build a debian image, the process dies at the debootstrap step:
```
COMMANDS:
                  verb: boot
               cmdline: 
DISTRIBUTION:
          Distribution: debian
               Release: buster
                Mirror: http://deb.debian.org/debian
          Repositories: http://repo.saltstack.com/py3/debian/10/amd64/3000/dists/

OUTPUT:
         Output Format: gpt_ext4
              Minimize: no
                Output: /mnt/blazing/mkosi/test/test.raw
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: no
                 QCow2: no
            Encryption: no
                Verity: no
              Bootable: yes
   Kernel Command Line: rhgb quiet selinux=0 audit=0 rw
       UEFI SecureBoot: no
        Boot Protocols: uefi

PACKAGES:
              Packages: iproute2
                        libnss-resolve
                        libnss-systemd
                        libnss-myhostname
                        libpam-systemd
                        casync
         Package Cache: /mnt/blazing/mkosi/test/mkosi.cache/debian~buster
           Extra Trees: /mnt/blazing/mkosi/test/mkosi.extra
        Skeleton Trees: none
          Build Script: none
         Build Sources: /mnt/blazing/mkosi/test
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
      Skip final phase: no
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

PARTITIONS:
        Root Partition: 1.0G
        Swap Partition: (disabled)
                   ESP: 256.0M
    XBOOTLDR Partition: (disabled)
       /home Partition: (disabled)
        /srv Partition: (disabled)
        /var Partition: (disabled)
    /var/tmp Partition: (disabled)

VALIDATION:
              Checksum: no
                  Sign: no
               GPG Key: default
              Password: set

HOST CONFIGURATION:
    Extra search paths: none

(...)

‣ Detaching image file complete.
Traceback (most recent call last):
  File "../mkosi/mkosi/mkosi", line 5092, in <module>
    main()
  File "../mkosi/mkosi/mkosi", line 5086, in main
    run_verb(a)
  File "../mkosi/mkosi/mkosi", line 5063, in run_verb
    build_stuff(args)
  File "../mkosi/mkosi/mkosi", line 4887, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "../mkosi/mkosi/mkosi", line 4692, in build_image
    install_distribution(args, workspace.name,
  File "../mkosi/mkosi/mkosi", line 2346, in install_distribution
    install[args.distribution](args, workspace, do_run_build_script)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "../mkosi/mkosi/mkosi", line 2017, in install_debian
    install_debian_or_ubuntu(args, workspace, do_run_build_script=do_run_build_script, mirror=args.mirror)
  File "../mkosi/mkosi/mkosi", line 1936, in install_debian_or_ubuntu
    run(cmdline, check=True)
  File "../mkosi/mkosi/mkosi", line 89, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=http://repo.saltstack.com/py3/debian/10/amd64/3000/dists/', '--merged-usr', 'buster', '/var/tmp/mkosi-1m59d16w/root', 'http://deb.debian.org/debian']' returned non-zero exit status 1.

```
It put other repositories as `--component`, but the manpage of debootstrap says 
```
--components=alpha,beta
              Use packages from the listed components of the archive.
```
So, it's not what's meant to be used. Further more, [this wiki page](https://wiki.debian.org/Debootstrap) says:
```
Debootstrap can only use one repository for its packages. If you need to merge packages from different repositories (the way apt does) to make a rootfs, or you need to automatically customise the rootfs, then use Multistrap. 
```
So, using debootstrap does not permit to use more than one repository and the `--repositories` should throw an invalid combination error (debian/ubuntu + --repositories)

**Comment by tmpm697** [comment]
I got the same issue, debian and ubuntu not able to build dues to my archlinux box can't pull packages from them.

```
[Files]
[Distribution]
Distribution=debian

[Output]
Format=gpt_ext4
Bootable=no
Output=image.raw
RootSize=2G

[Packages]
Cache=mkosi.cache
Packages=

[Validation]
Password=
```

```
> sudo mkosi --force

Unknown section in 'mkosi.default', ignoring: [Files]
Unknown key in section [Output] in 'mkosi.default', ignoring: RootSize=
‣ Removing output files...
‣ Removing output files complete.
DISTRIBUTION:
          Distribution: debian
               Release: unstable
                Mirror: http://deb.debian.org/debian

OUTPUT:
         Output Format: gpt_ext4
                Output: /home/user/test/image.raw
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: no
                 QCow2: no
            Encryption: no
                Verity: no
              Bootable: no

PACKAGES:
              Packages: none
         Package Cache: /home/user/test/mkosi.cache
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /home/user/test
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

PARTITIONS:
        Root Partition: 1.0G
        Swap Partition: (disabled)
    XBOOTLDR Partition: (disabled)
       /home Partition: (disabled)
        /srv Partition: (disabled)

VALIDATION:
              Checksum: no
                  Sign: no
               GPG Key: default
              Password: set

HOST CONFIGURATION:
    Extra search paths: none
‣ Detaching namespace...
‣ Detaching namespace complete.
‣ Setting up package cache...
‣ Setting up package cache /home/user/test/mkosi.cache complete.
‣ Setting up temporary workspace.
‣ Temporary workspace in /var/tmp/mkosi-7cb3gc6a is now set up.
‣ Creating partition table...
Checking that no-one is using this disk right now ... OK

Disk /home/user/test/.mkosi-2azfe6r9: 1 GiB, 1075838976 bytes, 2101248 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: 110675F6-B308-A84F-B302-3EA9BDFBB36A).
/home/user/test/.mkosi-2azfe6r9p1: Created a new partition 1 of type 'Linux root (x86-64)' and of size 1 GiB.
/home/user/test/.mkosi-2azfe6r9p2: Done.

New situation:
Disklabel type: gpt
Disk identifier: 110675F6-B308-A84F-B302-3EA9BDFBB36A

Device                             Start     End Sectors Size Type
/home/user/test/.mkosi-2azfe6r9p1  2048 2101214 2099167   1G Linux root (x86-64)

The partition table has been altered.
Syncing disks.
‣ Created partition table as /home/user/test/.mkosi-2azfe6r9.
‣ Attaching image file...
‣ Attached image file as /dev/loop0.
‣ Formatting root partition...
mke2fs 1.45.6 (20-Mar-2020)
Discarding device blocks: done
Creating filesystem with 262144 4k blocks and 65664 inodes
Filesystem UUID: 4aa2cbd7-5c11-4497-80c8-3973d3fa0d29
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376

Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

‣ Formatting root partition complete.
‣ Mounting image...
‣ Mounting image complete.
‣ Setting up basic OS tree...
‣ Setting up basic OS tree complete.
‣ Mounting Package Cache...
‣ Mounting Package Cache complete.
‣ Installing Debian...
I: Retrieving InRelease
```

I can't ping `archive.ubuntu.com`, either with ipv6 or ipv4 (here is ipv6)

```
PING archive.ubuntu.com(actiontoad.canonical.com (2001:67c:1360:8001::23)) 56 data bytes

--- archive.ubuntu.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

```
> nslookup archive.ubuntu.com
nslookup archive.ubuntu.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   archive.ubuntu.com
Address: 91.189.88.142
Name:   archive.ubuntu.com
Address: 91.189.88.152
Name:   archive.ubuntu.com
Address: 2001:67c:1562::18
Name:   archive.ubuntu.com
Address: 2001:67c:1360:8001::23
Name:   archive.ubuntu.com
Address: 2001:67c:1562::15
Name:   archive.ubuntu.com
Address: 2001:67c:1360:8001::24
```

I can ping ip address of `archive.ubuntu.com` as below:
```
> ping 91.189.88.142
PING 91.189.88.142 (91.189.88.142) 56(84) bytes of data.
64 bytes from 91.189.88.142: icmp_seq=1 ttl=52 time=245 ms

--- 91.189.88.142 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 245.426/245.426/245.426/0.000 ms
```

**Comment by tmpm697** [comment]
It's weird that ping resolve `archive.ubuntu.com` to `actiontoad.canonical.com`, I tried to open it on firefox and got permission denied, if I open `archive.ubuntu.com` on firefox, it resolves okay and return a accessable webpage.

The thing is, both archive.ubuntu.com or actiontoad.canonical.com are unsecure webpage (ssl not installed on them).

This can be the issue where ping or wget  or mkosi expect https on web it tries to connect to.

**Comment by DaanDeMeyer** [comment]
--repositories can only be used for configuring the default repositories to use. To add new repositories we'd need some extra discussion since they might use a distro specific format and options. If all supported package managers support including repos from another file, we could add a new option --extra-repositories that takes a file containing the extra repositories which are then included into the package manager configuration. We'll happily take a patch for something like that.

**Comment by lahtima** [comment]
For debian based distros, one way to support this would be just adding apt-get update and optionally apt-get dist-upgrade between debootstrap and package install. After that, you can pass repository config via skeleton tree (you would need to install ca-certificates always via debootstrap to support https repositories properly if done like this). For reference, this is possible to script into debootstrap second_stage_install but I'd like to have something similiar in mkosi itself, I just don't really have time currently to think how to add this support properly to other distros to make the patch not just be debian like specific.

**Comment by DaanDeMeyer** [comment]
We run `apt-get update` now after running debootstrap. as suggested by @lahtima, please use skeleton trees to pass along the repositories to use. We have the --repository-directory option now but it's not possible to have apt use repositories from the host system since it has to be executed inside the image so skeleton trees should be used instead.
