### ISSUE TITLE
Failing to run mkosi on Fedora 24

### ISSUE THREAD

**Issue by achanda** [systemd/mkosi#5]
I installed mkosi by cloning the repo and running `python setup.py install`. But when I try to run it, fails like this
```
[root@systemd-dev systemd]# mkosi
DISTRIBUTION:
          Distribution: fedora
               Release: 24

OUTPUT:
         Output Format: raw_btrfs
                Output: /root/systemd/image.raw
       Output Checksum: n/a
      Output Signature: n/a
Output nspawn Settings: n/a
             Read-only: no
        FS Compression: no
        XZ Compression: no

PACKAGES:
              Packages: none
    With Documentation: no
         Package Cache: /var/tmp/dnf-cache
           Extra Trees: none
          Build Script: /root/systemd/mkosi.build
         Build Sources: /root/systemd
        Build Packages: audit-libs-devel
                        autoconf
                        automake
                        bzip2-devel
                        cryptsetup-devel
                        dbus-devel
                        docbook-style-xsl
                        elfutils-devel
                        gcc
                        git
                        gnu-efi
                        gnu-efi-devel
                        gnutls-devel
                        gperf
                        intltool
                        iptables-devel
                        kmod-devel
                        libacl-devel
                        libblkid-devel
                        libcap-devel
                        libcurl-devel
                        libgcrypt-devel
                        libidn-devel
                        libmicrohttpd-devel
                        libmount-devel
                        libseccomp-devel
                        libselinux-devel
                        libtool
                        libxkbcommon-devel
                        libxslt
                        lz4-devel
                        make
                        pam-devel
                        pkgconfig
                        python3-devel
                        python3-lxml
                        qrencode-devel
                        xz-devel
       nspawn Settings: none

PARTITIONS:
              Bootable: yes
        Root Partition: 2.0G
        Swap Partition: (disabled)
                   ESP: 256.0M
       /home Partition: (disabled)
        /srv Partition: (disabled)

VALIDATION:
              Checksum: no
                  Sign: no
               GPG Key: default
‣ Detaching namespace...
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4, in <module>
    __import__('pkg_resources').run_script('mkosi==1', 'mkosi')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1657, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/mkosi-1-py2.7.egg/EGG-INFO/scripts/mkosi", line 1380, in <module>

  File "/usr/lib/python2.7/site-packages/mkosi-1-py2.7.egg/EGG-INFO/scripts/mkosi", line 1375, in main

  File "/usr/lib/python2.7/site-packages/mkosi-1-py2.7.egg/EGG-INFO/scripts/mkosi", line 59, in init_namespace

AttributeError: 'module' object has no attribute 'run'
```
Should I install mkosi in some other way?

**Comment by poettering** [comment]
Hmm, I fear my python-fu isn't good enough to know how to make this work...

**Comment by stefan-it** [comment]
`python` points to version *2.7* (on my Fedora 24 container) and in the error message you posted it was installed under the `/usr/lib/python2.7` path. So I guess `mkosi` won't run under Python in version *2.7*. What you can do: make sure that you've Python in version *3.x* installed. Instead of `python setup.py install` use: `python3 setup.py install`. Hopefully that works for you :)

**Comment by achanda** [comment]
That worked, thanks @stefan-it and @poettering
