### ISSUE TITLE
Fedora 25 build fails: AttributeError: 'Namespace' object has no attribute 'root_partno'

### ISSUE THREAD

**Issue by eliasp** [systemd/mkosi#58]
Trying to build a Fedora 25 image fails (running latest git master 10a8cf4).
Although I didn't specify to make use of LUKS (which also wouldn't make sense with a `directory`/`tar` output), it seems to end up in `luks_setup_all()`:

```
# mkosi -d fedora -t tar -o fedora
DISTRIBUTION:
          Distribution: fedora
               Release: 25

OUTPUT:
         Output Format: tar
                Output: /var/tmp/machines/fedora
       Output Checksum: n/a
      Output Signature: n/a
Output nspawn Settings: n/a
        XZ Compression: yes
            Encryption: no
                Verity: no

PACKAGES:
              Packages: none
    With Documentation: no
         Package Cache: none
           Extra Trees: none
          Build Script: none
         Build Sources: /var/tmp/machines
        Build Packages: none
     Post Inst. Script: none
       nspawn Settings: none

VALIDATION:
              Checksum: no
                  Sign: no
               GPG Key: default
              Password: default
\u2023 Detaching namespace...
\u2023 Detaching namespace complete.
\u2023 Setting up package cache...
\u2023 Setting up package cache /var/tmp/machines/.mkosi-383jzcvz complete.
\u2023 Setting up temporary workspace.
\u2023 Temporary workspace in /var/tmp/mkosi-_3jb65z3 is now set up.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4, in <module>
    __import__('pkg_resources').run_script('mkosi==1', 'mkosi')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.5/site-packages/mkosi-1-py3.5.egg/EGG-INFO/scripts/mkosi", line 2405, in <module>
  File "/usr/lib/python3.5/site-packages/mkosi-1-py3.5.egg/EGG-INFO/scripts/mkosi", line 2401, in main
  File "/usr/lib/python3.5/site-packages/mkosi-1-py3.5.egg/EGG-INFO/scripts/mkosi", line 2353, in build_stuff
  File "/usr/lib/python3.5/site-packages/mkosi-1-py3.5.egg/EGG-INFO/scripts/mkosi", line 2246, in build_image
  File "/usr/lib64/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.5/site-packages/mkosi-1-py3.5.egg/EGG-INFO/scripts/mkosi", line 403, in luks_setup_all
AttributeError: 'Namespace' object has no attribute 'root_partno'
```
Running this inside a privileged Fedora 25 Docker container on top of Debian 8.6.
The Docker container was started using:
```
docker run --tty --interactive --name=mkosi --volume=/var/tmp/machines:/var/tmp/machines --cap-add=SYS_ADMIN fedora /bin/bash 
```
`CAP_SYS_ADMIN` is required to make `unshare()` work, otherwise `mkosi` would fail like this:

```
\u2023 Detaching namespace...                                                                                                                                                     
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 1657, in <module>
    main()
  File "/usr/bin/mkosi", line 1652, in main
    init_namespace(args)
  File "/usr/bin/mkosi", line 73, in init_namespace
    unshare(CLONE_NEWNS)
  File "/usr/bin/mkosi", line 67, in unshare
    raise OSError(e, os.strerror(e))
PermissionError: [Errno 1] Operation not permitted
```

**Comment by fsateler** [comment]
Does #55 fix the issue? In particular, 	aa1bd27 should fix this

**Comment by lucaswerkmeister** [comment]
@eliasp #55 is merged now and should fix this, can you try again?

**Comment by keszybz** [comment]
Seems to work OK on F25 with `sudo ./mkosi -d fedora -t tar -o fedora --bootable=no`.
