### ISSUE TITLE
Bootable flag for raw_btrfs not supported under Debian unstable

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/mkosi#83]
I get an _unsupported variant_ error when trying to make a bootable raw_btrfs Debian image using mkosi under Debian unstable.

Here is the full traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/mkosi", line 2538, in <module>
    main()
  File "/usr/local/bin/mkosi", line 2534, in main
    build_stuff(args)
  File "/usr/local/bin/mkosi", line 2486, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/local/bin/mkosi", line 2384, in build_image
    install_distribution(args, workspace.name, run_build_script)
  File "/usr/local/bin/mkosi", line 1015, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi", line 833, in install_debian
    install_debian_or_ubuntu(args, workspace, run_build_script, args.mirror)
  File "/usr/local/bin/mkosi", line 778, in install_debian_or_ubuntu
    subprocess.run(cmdline, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--merged-usr', '--variant=minbase,btrfs-tools', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', 'unstable', '/var/tmp/mkosi-94qwlek9/root', 'http://httpredir.debian.org/debian']' returned non-zero exit status 1
```

**Comment by fsateler** [comment]
Indeed. https://github.com/systemd/mkosi/blob/master/mkosi#L776 needs to be changed to `cmdline[4]`, or better yet, adding `btrfs-tools` to `extra_packages`
