### ISSUE TITLE
Building a Fedora image fails on CentOS Stream 8

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#879]
/etc/os-release:

```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

```
git clone git@github.com:systemd/mkosi
sudo mkosi/bin/mkosi -d fedora
```

First failure:

```
~/mkosi (main)> sudo bin/mkosi -d fedora
‣ Detaching namespace
‣ Setting up temporary workspace.
‣ Temporary workspace set up in /var/tmp/mkosi-8qgm5g66
‣ Running second (final) stage…
‣  Creating image with partition table…
label: gpt
grain: 4096
first-lba: 40
size=6291456, type=4f68bce3-e8cd-4db1-96e7-fbcaf984b709, attrs=, name="Root Partition"
Disk /home/daandemeyer/mkosi/mkosi.output/.mkosi-cfyl3mx0: 3 GiB, 3221266432 bytes, 6291536 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> line 2: unsupported command

New situation:
Leaving.

Traceback (most recent call last):
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/daandemeyer/mkosi/mkosi/__main__.py", line 32, in <module>
    main()
  File "/home/daandemeyer/mkosi/mkosi/__main__.py", line 26, in main
    run_verb(a)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 7812, in run_verb
    manifest = build_stuff(args)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 7230, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 6927, in build_image
    raw = create_image(args, for_cache)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 803, in create_image
    args.partition_table.run_sfdisk(f.name)
  File "/home/daandemeyer/mkosi/mkosi/backend.py", line 343, in run_sfdisk
    run(cmd, input=spec.encode("utf-8"))
  File "/home/daandemeyer/mkosi/mkosi/backend.py", line 694, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/local/fbcode/platform009/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sfdisk', '--color=never', '--no-reread', '--no-tell-kernel', '/home/daandemeyer/mkosi/mkosi.output/.mkosi-cfyl3mx0']' returned non-zero exit status 1.
```

This happens because "grain" is unsupported by the version of sfdisk available in CentOS Stream 8 (util-linux 2.32.1). If I uncomment the grain option in mkosi I get:

```
~/mkosi (main)> sudo bin/mkosi -d fedora
‣ Detaching namespace
‣ Setting up temporary workspace.
‣ Temporary workspace set up in /var/tmp/mkosi-8hdagzz5
‣ Running second (final) stage…
‣  Creating image with partition table…
label: gpt
first-lba: 40
size=6291456, type=4f68bce3-e8cd-4db1-96e7-fbcaf984b709, attrs=, name="Root Partition"
Disk /home/daandemeyer/mkosi/mkosi.output/.mkosi-rlpxhqnt: 3 GiB, 3221266432 bytes, 6291536 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: 8B00C267-B5F3-9740-86C0-605E35452033).
/home/daandemeyer/mkosi/mkosi.output/.mkosi-rlpxhqnt1: The last usable GPT sector is 6291502, but 6293503 is requested.
Failed to add #1 partition: Invalid argument
Leaving.

Traceback (most recent call last):
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/daandemeyer/mkosi/mkosi/__main__.py", line 32, in <module>
    main()
  File "/home/daandemeyer/mkosi/mkosi/__main__.py", line 26, in main
    run_verb(a)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 7812, in run_verb
    manifest = build_stuff(args)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 7230, in build_stuff
    image = build_image(args, root, manifest=manifest, do_run_build_script=False, cleanup=True)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 6927, in build_image
    raw = create_image(args, for_cache)
  File "/home/daandemeyer/mkosi/mkosi/__init__.py", line 803, in create_image
    args.partition_table.run_sfdisk(f.name)
  File "/home/daandemeyer/mkosi/mkosi/backend.py", line 343, in run_sfdisk
    run(cmd, input=spec.encode("utf-8"))
  File "/home/daandemeyer/mkosi/mkosi/backend.py", line 694, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/local/fbcode/platform009/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sfdisk', '--color=never', '--no-reread', '--no-tell-kernel', '/home/daandemeyer/mkosi/mkosi.output/.mkosi-rlpxhqnt']' returned non-zero exit status 1.
```

CC @keszybz. I figure we should make an effort to support CentOS Stream 8 if we can.

**Comment by keszybz** [comment]
Hmm, well, sure. I think it'd be a lot of effort to support old `sfdisk` but if somebody prepares a patch…
