### ISSUE TITLE
mkosi build: TypeError: __init__() got an unexpected keyword argument 'user'

### ISSUE THREAD

**Issue by vt-alt** [systemd/mkosi#967]
We [got first intermittent](https://github.com/lkrg-org/lkrg/issues/187#issuecomment-1125049342) but now very frequent mkosi build error
https://github.com/lkrg-org/lkrg/runs/6404121625?check_suite_focus=true
https://github.com/lkrg-org/lkrg/runs/6393605191?check_suite_focus=true

```
Processing triggers for linux-image-unsigned-5.18.0-051800rc6-generic (5.18.0-051800rc6.202205082130) ...
‣ Detaching namespace
‣ Setting up package cache…
‣ Setting up package cache /home/runner/work/lkrg/lkrg/mkosi.cache complete
‣ Setting up temporary workspace.
‣ Temporary workspace set up in /var/tmp/mkosi-twddiqz0
‣ Running first (development) stage…
‣  Creating image with partition table…
‣  Created image with partition table as /home/runner/work/lkrg/lkrg/.mkosi-s3cpdumu
‣  Attaching /home/runner/work/lkrg/lkrg/.mkosi-s3cpdumu as loopback…
‣  Attached /dev/loop3
‣  Formatting root partition…
‣  Mounting image…
‣  Setting up basic OS tree…
‣  Mounting Package Cache
‣  Installing Ubuntu…
‣  Unmounting Package Cache
‣  Mounting Package Cache
‣  Running prepare script…
‣  Unmounting Package Cache
‣  Copying in build script…
‣  Copying in sources…
‣  (Unmounting image)
‣  (Detaching /dev/loop3)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 8061, in run_verb
    manifest = build_stuff(args)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7422, in build_stuff
    image = build_image(args, root, do_run_build_script=True)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7169, in build_image
    install_build_src(args, root, do_run_build_script, for_cache)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 3685, in install_build_src
    copy_git_files(args.build_sources, target, source_file_transfer=sft)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 3612, in copy_git_files
    c = run(["git", "-C", src, "ls-files", "-z", *what_files], stdout=PIPE, text=False, user=uid)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/backend.py", line 770, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'user'
Error: Process completed with exit code 1.
```
mkosi is installed from git: https://github.com/lkrg-org/lkrg/actions/runs/2300566135/workflow

**Comment by behrmann** [comment]
Ah, yes, `user=` was only added to `subprocess.Popen` in Python 3.9... I guess we need to find a different solution then, if we are to stay on 3.7 as the minimum version.

@vt-alt What system are you using this on, that it has Python 3.8? I'm not super firm in what Python releases run on different RH and Ubuntu versions, but I remember 3.7 in Debian buster is one of the older things I can think of.

**Comment by vt-alt** [comment]
Btw, why this bug is initially manifested itself only in the some of our test? We are always using latest version of mkosi from the git.

**Comment by behrmann** [comment]
I guess this was triggered only in some of your tests, because only `copy_git_files` uses this, so if you have tests without that, those will run fine. Using the beta ubuntu-22.04 worker should definitely solve the problem as well, but I don't think we can require being so bleeding edge :)
